### ISSUE TITLE
Make language optional for domain overrides

### ISSUE THREAD

**Issue by agentrickard** [agentrickard/domain#107]
In the Drupal 8 version, Domain Config is language sensitive (e.g. domain.config.example_com.en.config_item.yml).

We should allow a config setting to be active across an entire domain, with language optional.

That means check first for the domain/language combination, but fall back to domain-only.

* IF domain.config.example_com.en.config_item.yml
* ELSE domain.config.example_com.config_item.yml

**Comment by agentrickard** [comment]
This is causing a circular dependency failure that I don't quite understand.

**Comment by agentrickard** [comment]
This code is sitting in https://github.com/agentrickard/domain/tree/107-optional and it works fine through the UI, but running tests it throws a circular dependency error.

To see, run the Domain Config tests. 

Tests also fail if the 8.x.-1.x test is updated as follows:

```
<?php

/**
 * @file
 * Definition of Drupal\domain_config\Tests\DomainConfigTestBase.
 */

namespace Drupal\domain_config\Tests;

use Drupal\domain\Tests\DomainTestBase;
use Drupal\language\Entity\ConfigurableLanguage;

/**
 * Helper test methods for Domain Config testing.
 */
abstract class DomainConfigTestBase extends DomainTestBase {

  /**
   * Modules to enable.
   *
   * @var array
   */
  public static $modules = array('domain', 'domain_config', 'domain_config_test', 'language', 'locale');

  function setUp() {
    parent::setUp();
    ConfigurableLanguage::createFromLangcode('fr')->save();
  }

}
```

There is something going on inside the LanguageManager that I just can't follow.

**Comment by agentrickard** [comment]
If setting up the test environment is too much, here's the error message.

```
Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException: "Circular reference detected for service "language_manager", path: "language_request_subscriber -> language_manager -> config.factory -> domain_config.overrider"." at /Applications/MAMP/htdocs/drupal-8/core/lib/Drupal/Component/DependencyInjection/Container.php line 151 
```

**Comment by mevaibhav** [comment]
Hey Rickard, 

Appreciate your efforts migrating this Module to version 8. However , do you have any estimate time to complete this or the first dev version.

Any response would be welcomed

**Comment by agentrickard** [comment]
I do not, since I no longer do development day-to-day.

The APIs are, I believe, stable, so the current state could be considered an alpha.
