### ISSUE TITLE
Should domain_access_domain_source_alter be CLI aware?

### ISSUE THREAD

**Issue by davidDuymelinck** [agentrickard/domain#108]
When I have the domain and the domain access modules active and I want to create a drupal console command to duplicate a node using the Node::createDuplicate function, then i get an error in the domain_access_domain_source_alter function caused by `$options['active_domain']->id()` where $options['active_domain'] is null.

Because you never have a domain in CLI I suggest the function does nothing in this environment.

**Comment by agentrickard** [comment]
This is an interesting twist with console. In Drush, we used to pass a --url argument to avoid this.

Rather than being CLI-aware, this method needs to ensure that it has a domain object.

**Comment by agentrickard** [comment]
Let's go one step further. This should be fixed in Drupal\domain\HttpKernel\DomainPathProcessor::processOutbound().

**Comment by agentrickard** [comment]
You can test the change here -- #109.

**Comment by agentrickard** [comment]
Merged.
