### ISSUE TITLE
Ensure unique numeric ids for use with node access

### ISSUE THREAD

**Issue by agentrickard** [agentrickard/domain#115]
When creating a domain record, we use machine names as the primary key.

However, the node access system still requires a numeric id. Currently, we generate that from code in `Drupal\domain\DomainCreator::createNextId()`.

This routine needs to be checked so that we ensure:

* IDs are never repeated
* Test cases prove the above

That probably means storing a simple state variable, which might also need to be added to `domain.settings.yml`. A simple name like `domain_last_id` should work for this purpose.

**Comment by anishsheela** [comment]
Working on it.

**Comment by agentrickard** [comment]
We can add the test case to `Drupal\domain\Tests\DomainCreateTest` or spin up a `DomainUniqueIdTest` class.

**Comment by agentrickard** [comment]
I was looking through this today and I think we have to implement some form of "ok, you're deleting a domain, would you like to reassign users/content."

Shouldn't be too hard, given that we know what data to update.

**Comment by zerolab** [comment]
Is storing the last domain id as a state variable the best option? https://www.drupal.org/developing/api/8/state states [sic]

> You can reset a system, losing all state. Its configuration remains.

Having seen how even the D6/7 variables could fail dramatically on large site, I may be a bit overly cautious.

Your idea of reassigning the content on domain deletion is very good. If there are only 2 domains, should this step be skipped? i.e. all content from the deleted domain is automagically re-assigned to the remaining one.

**Comment by agentrickard** [comment]
State variable is, I think, the last resort, as State is not exportable and domains are. And the problem is that domain_id must be an integer (due to the {node_access} table), and is part of the export. So it becomes very easy to repeat ids of deleted domains.

In an ideal world, we could convert the machine_name to an integer value, perhaps using http://php.net/manual/en/function.crc32.php

As for reassigning content, yes, if only two domains, the assignment would not allow the user a choice (though it still needs to happen). We have this feature in the D7 version, I'm just giving it a higher priority.

**Comment by agentrickard** [comment]
Sadly, crc32 produces integers too large to store in the current table, and I don't want to push that to BIGINT.

**Comment by zerolab** [comment]
Hi Ken,

Had a quick look at the schema, and unless I am missing something glaringly obcious, it declares domain_id as an integer. MAX_INT_SIZE is at least 32-bit. This should hold the crc32 result, without the need to bump it to BIGINT.

Also, since the node_access table uses `int(10)`, i.e. unsigned int, we'd need to do something like:
```php
$id = sprintf('%u, crc32($domain->getHostname()));
```

**Comment by agentrickard** [comment]
Yes. This works.

**Comment by agentrickard** [comment]
It's going to possibly affect people using the module in production right now, but should be invisible unless people inspect the domain ids in the config.
