### ISSUE TITLE
 Add help text to domain overview screen

### ISSUE THREAD

**Issue by agentrickard** [agentrickard/domain#116]
The overview form (admin/config/domain) has no text explaining the page.  We can pull copy from the Drupal 7 `domain_overview_form` function, but it could use a rewrite for the new options.

The D8 form code is in `\Drupal\domain\DomainListBuilder`

**Comment by marcok** [comment]
do you mean text explaining?

**Comment by agentrickard** [comment]
Yes

**Comment by artreaktor** [comment]
How to get the default domain name in domain_help() ?
