### ISSUE TITLE
Provide common views support for attached fields

### ISSUE THREAD

**Issue by agentrickard** [agentrickard/domain#120]
The fields that are provided by default when using Domain Access link to the entity record. These are not useful. They should instead link to the host entity (the node).

* We need a filter handler for field_domain_access.
* We need a filter handler for field_domain_access_all_affiliates

We may also need custom handlers of other sorts for those.

**Comment by agentrickard** [comment]
OK, good work present in *16-views-handlers* which will make this easier.

**Comment by agentrickard** [comment]
Filters are working as desired, as are fields. Also added Actions for "all affiliates".

**Comment by artreaktor** [comment]
Having problems with `DomainAccessField::getItems()`
when using it in a node view:
`$domain = $item['rendered']['#options']['entity'];`
`'#options'` not set
I found working way to load domain objects:
`$domain = $object->getParent()->referencedEntities();`

Probably the error is related to the fact that the base view field is node and the domain object is incapsulated in EntityReference object.
Should we perform some initial check whether the domain_access_field is the base view field or n

**Comment by agentrickard** [comment]
Yes, we should.

Can you export your View and post it here so I can see what you're seeing?

**Comment by artreaktor** [comment]
Here's my articles view: 
[views.view.articles.zip](https://github.com/agentrickard/domain/files/125989/views.view.articles.zip)
Also I've noticed that field_domain_acces doesn't provide domain name for anonymous users

**Comment by agentrickard** [comment]
That's fascinating and will probably help track down the issue. I suspect an access check on the entity is causing that issue.

**Comment by agentrickard** [comment]
We forgot the 'view' case in DomainAccessControlHandler::CheckAccess(). Fixed.

**Comment by agentrickard** [comment]
The error occurs because your view does not have "Link label to the referenced entity" enabled. 

We can account for that, and for the other render options.

**Comment by agentrickard** [comment]
Fixed in #188.
