### ISSUE TITLE
Handle site name overrides -- perhaps as a new field?

### ISSUE THREAD

**Issue by agentrickard** [agentrickard/domain#123]
In earlier versions, the domain record label became the default site name. In the 7.x-.3.x version, this behavior became configurable.

We should decide how to handle this. It could be:

* A global option.
* A per-domain option
* Handled by Domain Config

Figure out which behavior we want and implement.

**Comment by nedjo** [comment]
> Handled by Domain Config

Given that Domain Config is the standard approach for overriding config per domain, it seems most consistent to just leave it at that. I suppose the argument could be made that you _always_ want to override the site name per domain, so it should be possible without an additional module, but on the balance it would seem just confusing to have certain overrides done one way, others another way.

**Comment by agentrickard** [comment]
Agreed.
