### ISSUE TITLE
Recreate the Domain Nav module

### ISSUE THREAD

**Issue by agentrickard** [agentrickard/domain#132]
There is still a use for Domain Nav, which provides a user-friendly menu block for navigating domains.

**Comment by vzinenko** [comment]
Hi @agentrickard , @andypost 
I can handle it.

**Comment by agentrickard** [comment]
I don't even think it needs to be a new module at this point. It can just be a block provided by the main module.

The key differences between this one and the domain switcher block (which is intended for testing/admins) are:

* Only show active domains
* Provide actual menu links, if necessary, in order to create the block from a menu

**Comment by vzinenko** [comment]
@agentrickard 
got it, thanks

**Comment by agentrickard** [comment]
See #390

**Comment by agentrickard** [comment]
Committed.
