### ISSUE TITLE
Allow selective access to domain record editing

### ISSUE THREAD

**Issue by agentrickard** [agentrickard/domain#134]
We have permissions in place that will allow users to edit some domain records, but not all.

Finish that implementation. See `\Drupal\domain\DomainAccessControlHandler`

**Comment by KittenDestroyer** [comment]
Started working on this issue

**Comment by agentrickard** [comment]
See https://www.drupal.org/node/2788623

**Comment by agentrickard** [comment]
OK, the move ahead here is that Domain management -- the core permission set that allows users to edit specific domains, needs to be handled by a field in the main module. 

That will let us expand the DomainAccessControlHandler to check that a user is assigned to manage specific domains.

Submodules (like Domain Alias) can then check that permission in addition to their own permission to see if a user can manage aliases for a specific domain.

The new field would be *field_domain_manager*. I am inclined not to make a "manage all" field, since that is a permission already.

**Comment by agentrickard** [comment]
See the `134-edit` branch.
