### ISSUE TITLE
Replace / inject the storage manager in DomainLoader.

### ISSUE THREAD

**Issue by agentrickard** [agentrickard/domain#144]
This is currently throwing an error when I tried to replace the entity manager, which has been deprecated.

**Comment by agentrickard** [comment]
See https://www.drupal.org/node/2549139

**Comment by bjaxelsen** [comment]
EntityManager has been deprecated, instead we should use EntityTypeManager.

I think it is not possible to inject it through the constructor:

1) When initializing the language manager service (and its dependencies) early during the page request by the Symfony service manager, Domain Config will be activated when loading language configuration.
2) Domain Config will depend on DomainLoader.
2) If we inject EntityTypeManager, it will requires injection of the string translation service.
3) The string translation service requires the language manager service, hence we have a circular dependency.

So we need to avoid this circular dependency and let the language manager service be fully initialized before we depend on it.

I am not quite sure how to solve it, i tried giving it a go in #165 but we may need to double check that this is the right solution.

**Comment by agentrickard** [comment]
That makes sense. I just couldn't follow the logic when the error came up. 

Oddly, I only had trouble during the tests. 

Thanks for tracking this down!

**Comment by agentrickard** [comment]
The fix in Domain Config works, but when I tried to inject the EntityTypeManager into the two loaders, I got the errors during tests again. So I may just drop it for now,

**Comment by agentrickard** [comment]
This is what I tried.

[test.patch.txt](https://github.com/agentrickard/domain/files/110463/test.patch.txt)

**Comment by agentrickard** [comment]
This turns out to be impractical, given the early request in the bootstrap process.
