### ISSUE TITLE
Use domain source for path rewrites

### ISSUE THREAD

**Issue by agentrickard** [agentrickard/domain#153]
All path rewriting logic should move to Domain Source.

**Comment by agentrickard** [comment]
See also #117

**Comment by agentrickard** [comment]
Most of this is done in https://github.com/agentrickard/domain/tree/153-domain-source but the tests are not working fully.

Can someone point me to proper documentation for how to generate a $#@! url in Drupal 8?

Something like the old url() function. Because the code in this branch is not behaving as expected.

**Comment by zerolab** [comment]
Would [URL::fromRoute()](https://api.drupal.org/api/drupal/core!lib!Drupal!Core!Url.php/function/Url%3A%3AfromRoute/8) do?

According to https://www.drupal.org/node/2491981 there are too many ways to generate a url.

Hope this helps.

**Comment by agentrickard** [comment]
Tim Millwood suggested $entity->toUri()->toString().

When I tried fromRoute() it did not add the entity metadata.
