### ISSUE TITLE
Make all affiliates default value configurable?

### ISSUE THREAD

**Issue by agentrickard** [agentrickard/domain#156]
Ideally, this value would be configurable per content type. Not sure if that is possible. Or if we just let field module handle things.

**Comment by andypost** [comment]
Any reason to have this field hardcode default value?
Sometimes it needs to have it `TRUE` for some bundles, so +1 to remove `default_value_callback` and allow to manage defaults with field ui

**Comment by agentrickard** [comment]
Right, I hadn't thought of that, since it used to be a setting.

Since this is a field, we can just read the default value.
