### ISSUE TITLE
Error reporting in domain_alias_domain_request_alter()

### ISSUE THREAD

**Issue by agentrickard** [agentrickard/domain#159]
Should probably do some error logging here if no match is returned.

**Comment by laughnan** [comment]
what does the acceptance criteria look like for this @agentrickard? just simply sending to watch dog?

**Comment by agentrickard** [comment]
So what this code is doing is as follows:

* Trying to load an alias that matches the request hostname
* Validating that that alias exists
* Validating that the alias matches a registered domain

The error capture we probably want to do is to log when the alias matches but fails to load a registered domain.

That might need to be wrapped in a try/catch, but I don't think we need to catch an exception here, as this error will not cause a failing request.

The message should be something like ```"Found matching alias $alias->getPattern() for host request $hostname, but failed to load matching domain with id $alias->domain_id". ```  Properly escaped of course.

**Comment by laughnan** [comment]
sounds good @agentrickard. i will look into this a bit this weekend. interested in seeing this module get to a beta/stable version for d8.

**Comment by agentrickard** [comment]
Committed.
