### ISSUE TITLE
Test that sort logic in DomainAliasLoader matches what is documented

### ISSUE THREAD

**Issue by agentrickard** [agentrickard/domain#163]
As it says in the title.

**Comment by marcok** [comment]
could you explain this a bit more in detail. are you saying a test needs to be written? "what is documented" documented where?

**Comment by agentrickard** [comment]
This documentation -- https://github.com/agentrickard/domain/blob/8.x-1.x/domain_alias/README.md (under Alias Matching).

The sorting happens in DomainAliasLoadee::sort(). There is a @TODO in the code.

I'd like to see some test case that confirms that the sort matching works as documented.

**Comment by agentrickard** [comment]
Fixed.
