### ISSUE TITLE
Drupal cache system makes it difficult to serve different homepage for each domain

### ISSUE THREAD

**Issue by bjaxelsen** [agentrickard/domain#166]
We need to be able to serve different homepages for each domain. Say we want to show `/node/1` as the homepage of http://localhost1/ and `/node/2` as the homepage of http://localhost2/.

Even though domain config can handle this, we run into problems with route caching in the Drupal cache system:

`\Drupal\Core\Routing\RouteProvider::getRouteCollectionForRequest()` defines cache ID's as `'route:' . $request->getPathInfo() . ':' .  $request->getQueryString()`.

For the home page this boils down to `route:/:`. This cache item will store the internal path to the homepage (say `/node/1`). Depending on the active domain when populating the cache, this can be a domain-specific homepage setting (overwriting system.site configuration).

Unlike the render cache, no cache context is added here. So home page setting for one domain will be active for all other domains as well. So even though we have made a configuration override for each domain, the cache will just serve the first cached domain setting for every domain.

**Possible solutions**

*1) Optional cache context in core for routes*
Extend the cache API:
* Using the kernel.request event any module can add in information to the request about 'route.cache.contexts'. The Request object has a public $attributes property that I think could be used for this.
* Domain config module can add an url context.
* `\Drupal\Core\Routing\RouteProvider::getRouteCollectionForRequest()` can pick up the route cache context and modify the cache ID (similar to the cache context of render caching).

*2) Register proxy path for domain-varied homepage*
* We create a small "domain homepage" module that allows us to set a per-domain homepage. 
* system.site > page.front configuration must be set to a path provided by this module (say `/domain-homepage`) - if not, a notice is shown on `admin/reports/status`
* When enabled, the module adds a homepage setting to `admin/config/domain/edit/{domain}`
* Because we control the caching of this path, it is easy to add in a cache contexts.

What do you think, @agentrickard?

**Comment by agentrickard** [comment]
This is closely related to #123, from a theory standpoint, and I thought we had fixed the issue of caching of site names (which came up earlier).

Does adding the required cache context of `url:site` fix this issue? See https://github.com/agentrickard/domain/blob/8.x-1.x/domain_config/README.md

If it doesn't, I think this belongs in DomainConfig. I would like to keep clean separation of function, so that the core module can be extended more easily.

However, I also worry that the cache context addition in the kernel request might have performance issues, so the smaller module might be wise. I think the real question here is "does this cache problem affect other parts of the config system?"

**Comment by agentrickard** [comment]
We probably need a test for this, too.

**Comment by agentrickard** [comment]
I was looking at the Config Translation module and don't see what, if anything is done about this problem there, which suggests that the language cache context might solve this problem for that module.

**Comment by bjaxelsen** [comment]
*Site name* is not the issue here.

Config Translation offers to translate the site name and site slogan, and this is already working fine with the Domain Configuration module as well (though there is no UI).

The problem is the default *home page* (because of the non-context-sensitive route caching of the home page), and Config Translation does not handle this. This setting is not present when you decide to translate the general information of your site (only site name and slogan).

Normally, the route is an internal thing and not really a problem for normal entities, as long as we can have domain-specific path aliases. So the domain-specific home page is really a special case.

Actually, the `\Drupal\Core\Routing\RouteProvider::getRouteCollectionForRequest()`is meant to allow for a collection of routes but eventually they get matched by path (and not domain / full url) in 
https://api.drupal.org/api/drupal/vendor%21symfony-cmf%21routing%21NestedMatcher%21UrlMatcher.php/class/UrlMatcher/8

Apparently, Symfony, does have great support for handling different domains (hostnames):
http://symfony.com/doc/current/components/routing/hostname_pattern.html

We might just bake a workaround into the Domain Config module. Maybe we could hard-code a configuration overwrite of the system.site page.front setting to a proxy route handled by Domain Config.

But it seem to me, that there might be a better, more lean Symfony approach?

Hmmm ... any suggestions?

**Comment by agentrickard** [comment]
No suggestions other than to handle it in Domain Config. My Symfony-fu is weak.

Interesting that you can't set a home page per language.

**Comment by agentrickard** [comment]
I am also concerned by this statement: "Normally, the route is an internal thing and not really a problem for normal entities, as long as we can have domain-specific path aliases."

Why is that required? We should move that to a new issue.

**Comment by bjaxelsen** [comment]
Sorry for the unclear statement! I was just trying to say that in most cases we don't have any problems regarding the routing caching, it is only the home page that causes an issue. No worries.

**Comment by bjaxelsen** [comment]
I think the issue around unwanted caching of the same route/path for homepages across domains (that should have separate homepages) is very similar to the inbound handling of domain-specific aliases in the upcoming Domain Source module.

Say we have a `http://domain1.com/contact` that should show a different node than `http://domain2.com/contact`, in both cases we would have route caches identified by cache ID `route:/contact:` and unwanted things would start to happen.

I think we need to go back to the clever caching guys and ask how to handle it.

I think it would be straightforward to add an optional route caching context to the $request object in $request->attributes. We could subscribe to KernelEvents::REQUEST and add in the url.site as route caching context. Then the cache ID would be something like `route:/contact::[url.site]=http://domain1.com`. Well, I am still trying to learn the caching-fu so I may miss out something here.

**Comment by agentrickard** [comment]
The above use-case is not how Domain Source works. It works on outbound link paths, not inbound. The use case described above is an advanced case (not considered essential for release) that was covered by Domain Path in Drupal 7.

Adding our cache ID to the route system via the request event does seem like a necessary step, however. I think that would go in Domain Config. The question is whether other modules might need it but not Domain Config. I can see a use-case where we have Domain Path and don't use Domain Config.  

It's a tough question about architecture. I wonder if it's possible to optionally enable that event handler.

**Comment by bjaxelsen** [comment]
Ahh, okay, then it is just a home page issue. It might be overkill to extend the Drupal core cache API.

Could we do it this way:

* We let Domain Config have an option to override the home page pr. domain. 

* If enabled, it will activate a custom inbound pathprocessor, that takes precedence over the core PathProcessorFront

In domain_config.services.yml It could be something like:
```
domain_path_processor_front:
    class: Drupal\domain_config\PathProcessor\DomainPathProcessorFront
    tags:
      - { name: path_processor_inbound, priority: 400 }
    arguments: ['@config.factory']
```

* This incoming pathprocessor will match the home path to a custom route defined by Domain Config 

```
class DomainPathProcessorFront implements InboundPathProcessorInterface {

  /**
   * A config factory for retrieving required config settings.
   *
   * @var \Drupal\Core\Config\ConfigFactoryInterface
   */
  protected $config;

  /**
   * Constructs a DomainPathProcessorFront object.
   *
   * @param \Drupal\Core\Config\ConfigFactoryInterface $config
   *   A config factory for retrieving the site front page configuration.
   */
  public function __construct(ConfigFactoryInterface $config) {
    $this->config = $config;
  }

  /**
   * {@inheritdoc}
   */
  public function processInbound($path, Request $request) {
    if ($path === '/' && $this->config->get('domain_config.settings')->get('front_override')) {
      $path = '/domain_config/homepage';
    }
    return $path;
  }
}
```
(alternatively, we could use the config.override system to override the system.site page.front setting - result should be the same)

* In domain_config.routing.yml we define this proxy route to handle delivering of the right homepage:

```
'domain_config.front_override':
  path: '/domain_config/homepage'
  defaults:
    _controller: '\Drupal\domain_config\Controller\HomepageOverrideController::homePage'
    _title: Home
  requirements:
    _access: 'TRUE'
```

* In domain/domain_config/src/Controller/HomepageOverrideController.php we implement a HomepageOverrideController::homePage() method that looks up the home page path ot the active domain (or domain/language)

* We forward to the controller class of the homepage (I am not sure how to match to the controller class of a different path, maybe through cloning the request with a diffrent path - may not be efficient)

* We forward to this controller (see http://symfony.com/doc/current/book/controller.html#forwarding-to-another-controller)

* We can cache by url.site and language if necessary.

-------------------

I am not quite sure if this is the best approach. @agentrickard could you or do you know anyone that could give input? It would be nice to get some good feedback rather than bump along towards a dead end.

**Comment by agentrickard** [comment]
Working on this in https://github.com/agentrickard/domain/tree/166-homepage

**Comment by agentrickard** [comment]
I have proper (and properly failing) test coverage in `domain_config/src/Tests/DomainConfigHomepageTest.php`

**Comment by agentrickard** [comment]
@bjaxelsen take a look at https://github.com/agentrickard/domain/pull/170, which _almost_ works.

**Comment by agentrickard** [comment]
I talked about this with Crell at length and he recommended a core patch.

https://www.drupal.org/node/2662196

**Comment by bjaxelsen** [comment]
Great! - I think the core patch is a straightforward solution that will make things much easier ☺

**Comment by wimleers** [comment]
Such great collaboration going on here!

But kind of sad it is not on d.o, then this would be far more discoverable.

**Comment by agentrickard** [comment]
Perhaps. The GitHub choice was entirely around forks and PRs -- which d.o. doesn't support -- when we had to make major code changes.

d.o. also isn't part of my daily routine anymore, but GH is, and recent changes there broke my workflow as a maintainer -- and yes, I filed a webmasters issue about that.

The plan is to move back to d.o. when we have alpha.
