### ISSUE TITLE
Invalidate render cache on Alias save

### ISSUE THREAD

**Issue by artreaktor** [agentrickard/domain#174]
#176

**Comment by zerolab** [comment]
I think a bit of tidy-up is needed. #176 is closed with a reference to https://github.com/agentrickard/domain/pull/172#issuecomment-180384361 which states 

> The cache invalidation should happen at the entity level, not in the save routine.

Based on #183, we need to add the renderer (and possibly other) cache context to the `list_cache_contexts` on DomainAlias entity. 

What would be a good test for this?
