### ISSUE TITLE
Documentation of (sub)domains setup

### ISSUE THREAD

**Issue by theodorosploumis** [agentrickard/domain#192]
Sorry if this question has already an answer but could not find anything. I want to test and contribute to the module but I cannot **find any instructions to setup the (sub)domains**. 

The [existing docs on D.O.](https://www.drupal.org/documentation/modules/domain) work only for 7.x version. I tried to include some of the ```*.services.yml``` that exist on the domain modules but had no lack.

Any help will be appreciated. I will add also any information I get here to the README.md.

Thanks.

**Comment by agentrickard** [comment]
I don't quite understand the question. Are you talking about cross-domain logins? 

See https://github.com/agentrickard/domain/blob/8.x-1.x/README.md and https://www.drupal.org/node/2391871
