### ISSUE TITLE
Add fallback when domains list is empty on domain overview page

### ISSUE THREAD

**Issue by artreaktor** [agentrickard/domain#198]
Getting 
Fatal error: Call to a member function get() on null here:
\Drupal::service('domain.loader')->loadDefaultDomain()->get('name');

**Comment by agentrickard** [comment]
This is coming from the Help text. Let's just remove the domain name from the help text, as it causes issues.

**Comment by artreaktor** [comment]
I agree, the simpler the better. Added new commit
