### ISSUE TITLE
DomainConfigOverrider returns empty $overrides

### ISSUE THREAD

**Issue by artreaktor** [agentrickard/domain#204]
This is related to #196 
Background: I have four languages enabled (en,de,zh-hant,uk). For de.example.com I need Chinese and Ukrainian to be disabled. 
So, i have
domain.config.de_example_com.language.entity.uk.yml
and
domain.config.de_example_com.language.entity.zh-hant.yml
for that. Everything works well until I switch to the default (en) language:
The last-added language isn't overridden in language-switcher and translation interface.

This happens when $this->domain is empty in DomainConfigOverrider::loadOverrides()
Temporary solved with
`$this->domain = $this->domainNegotiator->getActiveDomain(TRUE);`
in DomainConfigOverrider::initiateContext() 

The domain negotiator doesn't return active domain under certain circumstances. Probably it is related to caching somehow. Where is the right point to fix this?

**Comment by agentrickard** [comment]
Well, first I do not understand the names of the YML override files.

* `domain.config.de_example_com.language.entity.uk.yml` is malformed and should be `domain.config.de_example_com.uk.yml` and `domain.config.de_example_com.language.entity.zh-hant.yml` should be `domain.config.de_example_com.zh-hant.yml`.

If changing the names of the files doesn't solve the issue, then it's a matter of tracking through the call stack to see when the initiateContext() code is being called and fails. If we knew what the condition was, then we could figure an answer.

**Comment by agentrickard** [comment]
You might also look at this method, which might be setting the wrong language context.

```
  /**
   * {@inheritdoc}
   */
  public function getCacheableMetadata($name) {
    $this->initiateContext();
    $metadata = new CacheableMetadata();
    if (!empty($this->domain)) {
      $metadata->addCacheContexts(['url.site', 'languages:language_interface']);
    }
    return $metadata;
  }
```

It's not clear to me which cache context we should use for languages.

**Comment by agentrickard** [comment]
Fixed. 

   d460894..39947dd  8.x-1.x -> 8.x-1.x
