### ISSUE TITLE
 Exporting config may break subsequent site installs

### ISSUE THREAD

**Issue by agentrickard** [agentrickard/domain#212]
This came up on another project using the check_fields() trick to install.

After installing and configuring workbench access, I exported configuration with drush cex. The site functions properly. If I re-run a site install, the configuration does not properly import and the site install fails.

Specifically, I receive the following error message:

(I'll find it and post it)

Adding a try/catch around workbench_access_confirm_fields() in workbench_access.module() allows the build to finish properly.

**Comment by zerolab** [comment]
Just encountered this.

And an additional issue with domain_config. We have:
- system.site.yml
- domain.config.domain_1.system.site.yml
- domain.config.domain_2.system.site.yml

`Rename operation for simple configuration. Existing configuration system.site and staged configuration` The config importer sees `domain.config.domain_2.system.site.yml` as a rename of `system.site.yml` even though they are completely different.

**Comment by agentrickard** [comment]
That's a totally separate issue.

**Comment by zerolab** [comment]
Created #229 as I should have in the first place
