### ISSUE TITLE
Test against Drupal 8.1

### ISSUE THREAD

**Issue by agentrickard** [agentrickard/domain#214]

**Comment by zerolab** [comment]
Travis is already set up to test against 8.1.x -  [.travis.yml:L25](https://github.com/agentrickard/domain/blob/8.x-1.x/.travis.yml#L25)

We should update `.travis.yml` to test against 8.1.x and 8.2.x. And fail properly when any of the tests do. 
Currently domain_access, domain_config and domain_source have failing tests.

**Comment by agentrickard** [comment]
Well, I also realized yesterday that I have been working without E_STRICT set, so ther may be minor issues in the code.

I would set the travis file to add 8.2.x, but not remove 8.0.x just yet.

**Comment by agentrickard** [comment]
Added in https://github.com/agentrickard/domain/commit/b2e2367af78b5f95cc2551f5e21fc47a24071c7d

**Comment by zerolab** [comment]
Shouldn't this be closed as you added 8.2.x in b2e2367 ?
