### ISSUE TITLE
Restricting access to DOMAIN_ACCESS_ALL_FIELD in nodes causes SQL exception

### ISSUE THREAD

**Issue by claire-remy** [agentrickard/domain#217]
This seems to be a known drupal 8 issue : [https://www.drupal.org/node/2609252](url) 
In the meantime, users who don't have access cannot add nodes; 
Maybe change the #type to 'hidden' until this issue is fixed ? 

SQL Exceptions raised : 
Drupal\Core\Database\DatabaseExceptionWrapper: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'field_domain_all_affiliates_value'
Drupal\Core\Entity\EntityStorageException: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'field_domain_all_affiliates_value'

**Comment by agentrickard** [comment]
Fun.
Is this testable?

**Comment by claire-remy** [comment]
I am not familiar with SimpleTest but I guess you would just have to test whether adding a Node with an account which doesn't have the permission 'publish to any domain' throws an exception.

**Comment by agentrickard** [comment]
That's a fairly easy test to write and I recommend you learn how to do so.

I don't have time to write test coverage for everything.

**Comment by claire-remy** [comment]
I will look into it.

**Comment by agentrickard** [comment]
You can probably drop it into Drupal\domain_access\Tests\DomainAccessFieldTest, which checks that the domain fields are properly rendered but doesn't actually submit the forms.  See lines 80-92 of that file, which checks that the domain fields are not shown.

What we'd want to do is try to submit that form and test the results.

**Comment by claire-remy** [comment]
Thanks, I'll have a look at it and get back to you :)

**Comment by zerolab** [comment]
bb2ba48 in #226 has tests for the node and user save operation when the field is hidden.

The [patch from comment 5](https://www.drupal.org/files/issues/field-schema-2609252-5.patch) from https://www.drupal.org/node/2609252 avoids the exception.
