### ISSUE TITLE
Provide Views access control

### ISSUE THREAD

**Issue by zerolab** [agentrickard/domain#221]
Would be good to be able to restrict access per domain as we have in D7

**Comment by agentrickard** [comment]
That should be possible. I'm a little surprised that the Context system -- which works for Panels -- doesn't work here already.

**Comment by agentrickard** [comment]
I have most of this code working in branch 221-views-access.

It looks like I have to alter the route, which I am a bit uncertain about.

**Comment by zerolab** [comment]
Looking at at the Role [@ViewsAccess plugin](ihttps://api.drupal.org/api/drupal/core!modules!user!src!Plugin!views!access!Role.php/8.2.x), they do the same:

```php
  /**
   * {@inheritdoc}
   */
  public function alterRouteDefinition(Route $route) {
    if ($this->options['role']) {
      $route->setRequirement('_role', (string) implode('+', $this->options['role']));
    }
  }
```

so it must be the correct way.

**Comment by agentrickard** [comment]
Except that they probably have additional code (not in this plugin) that handles that Routing extension? I haven't looked at that yet, all I did was copy and alter the Plugin.

**Comment by agentrickard** [comment]
It looks like we have to expand the current DomainAccessCheck::applies() to check to see if the _domain requirement is set. If it is, then our response to DomainAccessCheck::access() would also be different (and based on the Plugin's response in addition to the initial check).

**Comment by agentrickard** [comment]
This was a bit weird, but I think this will work. #267

**Comment by agentrickard** [comment]
Fixed.
