### ISSUE TITLE
The domain_validate hook needs tests

### ISSUE THREAD

**Issue by zerolab** [agentrickard/domain#222]
[Discussion](https://github.com/agentrickard/domain/pull/218#discussion_r63228019) from the following change:

```diff
-    \Drupal::moduleHandler()->invokeAll('domain_validate', $error_list, $hostname);
+    \Drupal::moduleHandler()->invokeAll('domain_validate', array($error_list, $hostname));
```

The test hook implementation would need to go in `domain_test.module`

`domain.api.php` defines an alter hook (`hook_domain_validate_alter()`) where as the like above is a simple hook. So it should probably be changed to \Drupal::moduleHandler()->alter('domain_validate', $error_list, $hostname, $context);

**Comment by agentrickard** [comment]
See also #11.
