### ISSUE TITLE
Gracefully handle regular users without a domain assigned updating their account

### ISSUE THREAD

**Issue by zerolab** [agentrickard/domain#225]
Scenario:

- Domain Access added to existing site
- Not all users are assigned to a domain
- A regular user without the `assign domain editors` or `assign editors to any domain` permission edits their account (e.g. changes password)
- On save:

```
The website encountered an unexpected error. Please try again later. Drupal\Core\Entity\EntityStorageException: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'field_domain_all_affiliates_value' at row 1: INSERT INTO {user__field_domain_all_affiliates} (entity_id, revision_id, bundle, delta, langcode, field_domain_all_affiliates_value) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5); Array ( [:db_insert_placeholder_0] => 86 [:db_insert_placeholder_1] => 86 [:db_insert_placeholder_2] => user [:db_insert_placeholder_3] => 0 [:db_insert_placeholder_4] => en [:db_insert_placeholder_5] => ) in Drupal\Core\Entity\Sql\SqlContentEntityStorage->save() (line 757 of core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).
```

The domain access fields visibility is changed in `domain_access_form_user_form_alter()`. I suspect implementing `hook_entity_field_access()` is a better call and will remove the need for both `domain_access_form_node_form_alter()` and `domain_access_form_user_form_alter()`.

**Comment by agentrickard** [comment]
Makes sense. Would that also correct the issue described in #217?

**Comment by zerolab** [comment]
Gah, I thought this looked familiar. Will give it a try to see it it fixes it.

Closing as duplicate of #217
