### ISSUE TITLE
adding a block crashes due to error in Domain condition

### ISSUE THREAD

**Issue by joachim-n** [agentrickard/domain#227]
When I try to add a block, the modal window gets stuck. Opening the 'place block' link in another tab shows the error message:

> Warning: array_map() expects parameter 1 to be a valid callback, class 'Drupal\Component\Utility\Html' does not have a method 'checkPlain' in modules/domain/domain/src/Plugin/Condition/Domain.php on line 68

checkPlain() was moved to SafeMarkup::checkPlain() at some point in the D8 dev cycle.

**Comment by zerolab** [comment]
Introduced in https://github.com/agentrickard/domain/commit/1ff4051622cecef2e4d56e091df75683bafc1549

was supposed to be `Html::escape`
