### ISSUE TITLE
The configuration importer sees domain.config export as rewrite of core configuration

### ISSUE THREAD

**Issue by zerolab** [agentrickard/domain#229]
Encountering an interesting issue with domain_config. We have:
- system.site.yml
- domain.config.domain_1.system.site.yml
- domain.config.domain_2.system.site.yml

The config importer sees `domain.config.domain_2.system.site.yml` as a rename of `system.site.yml` even though they are completely different. Trying to run it fails with `Rename operation for simple configuration. Existing configuration system.site and staged configuration`

**Comment by agentrickard** [comment]
How do you replicate this error? I haven't tried any imports yet.

**Comment by zerolab** [comment]
We encountered it in 2 situations:

1. Existing build started using Domain. We tweaked and exported configuration. Created the `domain.config.*` YAML files to set different home pages. The error appears when deploying to staging/production. Worked around it by moving out the yml seen as a rename, running the import, moving it back in, re-running the import.
2. The other scenario is setting up new developer builds. We have a VM per build. On spinning up a new VM a shell script does:

```sh
drush --yes --verbose \
  site-install config_installer \
  install-select-language-form.langcode=en \
  config-installer-sync-configure-form.sync_directory=../config/sync/ \
  --db-url=mysql://vagrant:vagrant@localhost/drupal8_sitename \
  --account-name=admin --account-pass=password --account-mail=aeon@torchbox.com
```

among other things like `composer update` and so on.

**Comment by agentrickard** [comment]
This seems like a core issue to me. What are we missing in our implementation? Do we know how Config Translation handles this issue?

**Comment by zerolab** [comment]
Hi Ken,

It turns out this was a big PEBCAK! Somehow the two files had the same UUID o_O

Sorry about the noise!

**Comment by agentrickard** [comment]
O THANK THE GODS!

**Comment by zerolab** [comment]
I owe you a few PRs :D

Domain Config works very well. Now to find the time to implement an UI for this.

**Comment by agentrickard** [comment]
I don't think you **can** build a UI for it. See #15 and https://www.drupal.org/node/2677124

**Comment by agentrickard** [comment]
The work I did before stopping is in the 15-ui branch.

https://github.com/agentrickard/domain/tree/15-ui
