### ISSUE TITLE
Release on Drupal org

### ISSUE THREAD

**Issue by itsekhmistro** [agentrickard/domain#236]
Hi Ken,

Could you clarify current plans about publishing a release (alpha or something) of Domain module on Drupal.org?

Thank you in advance.

**Comment by zerolab** [comment]
@itsekhmistro see the repo README

> The GitHub issues are grouped under three milestones:
> 
> 1. Alpha -- items required for a test release. When this is complete, we will roll an alpha1 release on Drupal.org.
> 2. Beta -- items considered critical features for a release. When complete, we will roll a beta release on Drupal.org.
> 3. Final -- items required for a stable, secure release on Drupal.org.

See the [remaining tasks](https://github.com/agentrickard/domain/milestones/Alpha%20) for the Alpha release.

Pull requests are welcome.
