### ISSUE TITLE
Domain Access fields: Improve UI for node form 

### ISSUE THREAD

**Issue by bjaxelsen** [agentrickard/domain#239]
The node edit form places advanced fields (promote to front, sticky, menu settings etc.) in an accordion to keep the basic content editing simple and usable. I think we should do the same for the Domain Access fields.

Also, we might want to provide the current domain as default if no default is given. To some users the concept of controlling domain access can be somewhat complicated, so if we can turn this into something that most users don't need to take care of, it would be better.

How about adding this form alter in domain_access.module?

```
/**
 * Implements hook_form_BASE_FORM_ID_alter().
 * 
 * Set a domain for domain access by default and move Domain-specific fields to
 * an advanced tab
 */
function domain_access_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (isset($form['field_domain_access'])) {
    if(empty($form['field_domain_access']['widget']['#default_value'])) {
      // Get current domain
      $domain = \Drupal::service('domain.negotiator')->getActiveDomain()->id();
      if (isset($form['field_domain_access']['widget']['#options'][$domain])) {
        $form['field_domain_access']['widget']['#default_value'] = [$domain];
      }
    }
    // Move to the tabs on the node form
    $form['field_domain_access']['#group'] = 'domain';
    if (isset($form['field_domain_all_affiliates'])) {
      $form['field_domain_all_affiliates']['#group'] = 'domain';
    }
    $form['domain'] = [
      '#type' => 'details',
      '#title' => t('Domain'),
      '#group' => 'advanced',
      '#attributes' => [
        'class' => ['node-form-options']
      ],
      '#attached' => [
        'library' => ['node/drupal.node'],
      ],
      '#weight' => 100,
      '#optional' => TRUE
    ];
  }
}
```

**Comment by agentrickard** [comment]
That default to current domain should already be set. See testDomainAccessDefaultValue().

Putting it in the sidebar would, to me, be a configuration option, which is what we did in D7. 

Can we make that part conditional on a setting, but default to TRUE?

**Comment by agentrickard** [comment]
Also wondering: how does this play with modules like Field Group?
