### ISSUE TITLE
Document how Domain Config can override any type of configuration

### ISSUE THREAD

**Issue by nedjo** [agentrickard/domain#240]
Domain Config can be used to override any type of configuration, but:
* The README file and test module overrides are limited to simple configuration.
* The steps to override configuration of a type other than simple configuration are non-intuitive.

**Comment by agentrickard** [comment]
Long time no see @nedjo!

Do you think we should include a more complex test case?

**Comment by nedjo** [comment]
Couldn't hurt. I've successfully installed config entity overrides by manually importing them but haven't tested doing so from a module.

**Comment by agentrickard** [comment]
We have the testing pattern in domain_confg_test. It's a nice-to-have, not a must.
