### ISSUE TITLE
Trouble accessing nodes from other domain

### ISSUE THREAD

**Issue by belaustegui** [agentrickard/domain#248]
I have a multisite installation of Drupal 8 with two domains: _Domain A_ and _Domain B_. In Drupal I have enabled the following modules:

* domain
* domain_access
* domain_content

After enabling the modules I can choose the affiliate domains for my nodes without problem.
The thing is: I have a node affiliated to _Domain A_, but I can see it also in _Domain B_ (even for an anonymous user).
I've taken a look at the `domain_access_node_access` implementation and I've seen that it only acts when the operation is `update` or `delete`. I don't know if this is by design or not.

Should I implement my own `hook_node_access` to avoid showing nodes affiliated to a different domain to anonymous users? Or am I missing something in the configuration?

**Comment by agentrickard** [comment]
That is by design. That access hook only affects editing, not View.

You want to look at what's in the {node_access} table and being stored via domain_node_access_records().

Given that you are in multisite, you also need to ensure that sites.php maps your domains to the proper installation.
