### ISSUE TITLE
Unable to get alias working

### ISSUE THREAD

**Issue by mickaelperrin** [agentrickard/domain#253]
Hi,

Thanks for working on the port to Drupal 8 of this module. I fighted with it a good part of the day, got config override working but only with direct match. I deep dive in the code and there are some parts I don't undestand. Could you give me some infos ?

## What I want to achieve

I intend to deploy 4 websites on the same Drupal. They will share some common entity types but will have for example specific users and themes.

So far, I tried the config with two domain and the following synonyms domain (depending on the configuration / development stage):

- www.domain.fr : www.domain.fr.docker, devel.domain.fr.docker, debug.domain.fr.docker
- extranet.domain.fr : extranet.domain.fr.docker, devel.extranet.domain.fr, debug.extranet.domain.fr

## What I have done so far 

Create two domains : 

- extranet.domain.fr with the following aliases extranet.domain.fr.docker, devel.extranet.domain.fr, debug.extranet.domain.fr
- www.domain.fr with the following aliases www.domain.fr.docker, devel.domain.fr.docker, debug.domain.fr.docker, and set as **default**

## What I don't understand

When accessing the domain `extranet.domain.fr.docker`, the `setRequestDomain` method is called and the `$domain` is set to the default domain before the `domain_request_allter` hook is called.

Is it intended ?

Do you have some tips to achieve what I want ?

**Comment by mickaelperrin** [comment]
Just added the PR #254, to explicit what I did to resolve this issue.

**Comment by agentrickard** [comment]
This does indeed look like the correct solution.

**Comment by agentrickard** [comment]
Fixed in PR #255.  Nice work!
