### ISSUE TITLE
Menu links do not pass entity data for Domain Source

### ISSUE THREAD

**Issue by bran** [agentrickard/domain#259]
<img width="544" alt="pathprocessormanager_php_-_lmi3dim_-____sites_lmi3dim_" src="https://cloud.githubusercontent.com/assets/111225/17605234/4a1864fa-5fce-11e6-8d23-d574809fe1eb.png">

I'm having trouble with Domain Source not rewriting menu links pointing to nodes.

For example, if a menu link points to /products which is an alias of /node/11 or entity:node/11 in the menu table, $options['entity_type'] and $options['entity'] are not set for the processor.

**Comment by agentrickard** [comment]
It's probably an issue with how the data is loaded, not the proccessor order. This need to have the entity inside the $options is something I documented for Drupal core over 4 years ago, and it's frustrating to see that it still isn't consistently implemented.

I was only testing against page-based node links, so this means that we have to account for the fact that the $entity might not be present.

Personally, I think this is a core bug that needs fixing. Our handling of URLs is maddening.

**Comment by agentrickard** [comment]
This is going to need a test, too.

**Comment by agentrickard** [comment]
See the #262 PR for a proposed solution. After updating the code, run a cache reset.

**Comment by agentrickard** [comment]
I think the work in #262 accounts for this case now.

**Comment by agentrickard** [comment]
Fixed.
