### ISSUE TITLE
warning clearing cache upgrading to alpha3

### ISSUE THREAD

**Issue by davidgil** [agentrickard/domain#265]
Hi,

i just upgrade from alpha1 to alpha3 and when i do "drush cr", i have lots of warnings like this:

in_array() expects parameter 2 to be array, null given in Drupal\domain\Access\DomainAccessCheck-&gt;checkPath() (line 59 of   [warning]
modules/contrib/domain/domain/src/Access/DomainAccessCheck.php).
Drupal\domain\Access\DomainAccessCheck-&gt;checkPath(&#039;/admin/structure/display-modes/view/manage/{entity_view_mode}/translate/{langcode}/add&#039;)
(Line: 48)
Drupal\domain\Access\DomainAccessCheck-&gt;applies(Object) (Line: 135)
Drupal\Core\Access\CheckProvider-&gt;applies(Object) (Line: 82)
Drupal\Core\Access\CheckProvider-&gt;setChecks(Object) (Line: 186)
Drupal\Core\Routing\RouteBuilder-&gt;rebuild() (Line: 83)
Drupal\Core\ProxyClass\Routing\RouteBuilder-&gt;rebuild() (Line: 1141)
drupal_flush_all_caches() (Line: 51)
drupal_rebuild(Object, Object) (Line: 291)
drush_cache_rebuild() (Line: 366)
_drush_invoke_hooks(Array, Array) (Line: 217)
drush_command() (Line: 185)
drush_dispatch(Array) (Line: 67)
Drush\Boot\BaseBoot-&gt;bootstrap_and_dispatch() (Line: 66)
drush_main() (Line: 12)

solved with this change in DomainAccessCheck class:

  public function checkPath($path) {
    $allowed_paths = $this->configFactory->get('domain.settings')->get('login_paths');
    if (!empty($allowed_paths)) {
      $paths = preg_split("(\r\n?|\n)", $allowed_paths);
    }
    if (**!empty($paths) &&** in_array($path, $paths)) {
      return FALSE;
    }
    return TRUE;
  }

**Comment by zerolab** [comment]
This is a change from #264.
I think it is missing an install hook to add the missing paths. Or ` $this->configFactory->get('domain.settings')->get('login_paths');` could become ` $this->configFactory->get('domain.settings')->get('login_paths', '/user/login\r\n/user/password'');` (that is provide `/user/login\r\n/user/password'` as the default.

Either way a PR is most welcome, @davidgil

**Comment by agentrickard** [comment]
Yes, I was wondering about that. Since we don't have an alpha-to-alpha update script.

You can fix this by going to the Domain settings page and adding the following, then saving:

```
/user/login
/user/password
```

**Comment by agentrickard** [comment]
The !empty should be added, because there is a case where people will disable this entirely and force login from the primary domain.

**Comment by agentrickard** [comment]
See #266

**Comment by agentrickard** [comment]
Fixed. I'll go ahead and roll alpha4.
