### ISSUE TITLE
Is there a plan to bring domain_settings into D8?

### ISSUE THREAD

**Issue by kdebisschop** [agentrickard/domain#276]
This duplicates https://www.drupal.org/node/2797459 - at this point I'm not sure where you prefer to track issues. Let me know and I will close one or the other.

I imagine this is a known pain point - many modules I would like to use on my site are not built to store settings for multiple domains. From what I can see, domain_settings was designed to solve that problem. So I could have my different comscore tracking tag for each site and so on.

Are there plans to port domain settings to D8? If porting to D8 is an option, is there something I can do to help? I think this is going to be a significant issue for my company, so I am motivated to help if I can.

**Comment by agentrickard** [comment]
I'd like to, but cannot because there is no way to know that a settings form is being used. 

See #15 and the core issue linked there, which I am doing a Core Conversation about at DrupalCON Dublin.
