### ISSUE TITLE
UI to define a homepage for each domain

### ISSUE THREAD

**Issue by dmouse** [agentrickard/domain#277]
I want to customize the homepage in each domain, my first approach it defines the value on each domain in `Drupal\domain\DomainForm` to create the homepage field (image below)

![image](https://cloud.githubusercontent.com/assets/198571/19540191/5c9befc6-9623-11e6-9e14-5e983aae18e8.png)

Internally We need to create a new `PathProcessor` to read information for each domain

``` php
<?php

namespace Drupal\domain\PathProcessor;

/**
 * Processes the inbound path by resolving it to the front page if empty. 
 */
class PathProcessorDomainHomepage implements InboundPathProcessorInterface, OutboundPathProcessorInterface { 

}
```

What do you think about it?

**Comment by dmouse** [comment]
My first approach is using nodes, maybe this can be changed for any path into a Drupal site.
See this pull request #278

**Comment by dmouse** [comment]
Do you have any feedback for me?

**Comment by agentrickard** [comment]
Yes, I put it in the PR just now.
