### ISSUE TITLE
Domain-scoped URL Aliases

### ISSUE THREAD

**Issue by pimpreneil** [agentrickard/domain#280]
Hi,

I would like to have the same URL alias used on two different domains but linking to two different nodes.

For example, having `example.com/home` linking to node 1 and having `example.com.cn/home` linking to node 2.

For what I saw, it is not currently possible as Drupal prevents having two nodes with the same alias (or at least not in the same language). Is there any solution to this use case using this module?

Thanks

**Comment by agentrickard** [comment]
We've done it in Drupal 7 with Domain Path, and that module would need to be updated to Drupal 8. https://www.drupal.org/project/domain_path

There are some UI challenges, I suspect, and it needs the custom Route handling that Domain Source is using to allow caching by domain.

That said, I think it's out of scope for this module package, but the APIs and structures are in place for that port to be built.

**Comment by agentrickard** [comment]
See https://www.drupal.org/node/2821633

**Comment by pimpreneil** [comment]
@agentrickard thank you very much!
Right timing there it seems! Hope that this patch will arrive in your module soon !

**Comment by agentrickard** [comment]
Well, I don't intend to include Domain Path here, and I don't really have time to maintain it.

Hopefully one of the patch authors will be willing to maintain it.

**Comment by pimpreneil** [comment]
@agentrickard allright, btw, theapi's domain_path patch works well.
I am closing the issue
