### ISSUE TITLE
Domain Source: Path rewrite doesn't function for Drupal url alias

### ISSUE THREAD

**Issue by lulbina** [agentrickard/domain#281]
getEntity() in DomainSourcePathProcessor returns NULL when the path parameter contains alias and thus it doesn't rewrite the path to switch from base url of domain 1 to base url of domain 2. It works only when the paths are like: /node/1 or /node/2 but not for the paths that look like: /about-us.

With my custom patch it works, but I was asking if I was missing something in my Config.

**Comment by agentrickard** [comment]
No, that's probably an oversight in the code. Can you post the patch here?

**Comment by lulbina** [comment]
Hi agentrickard. Here you have the patch that is working for me.

diff --git a/domain_source/src/HttpKernel/DomainSourcePathProcessor.php b/domain_source/src/HttpKernel/DomainSourcePathProcessor.php
index 14462b8..7235637 100644
--- a/domain_source/src/HttpKernel/DomainSourcePathProcessor.php
+++ b/domain_source/src/HttpKernel/DomainSourcePathProcessor.php
@@ -133,8 +133,10 @@ class DomainSourcePathProcessor implements OutboundPathProcessorInterface {
             break;
           }
         }
+        // Get Node path if alias.
+        $node_path = \Drupal::service('path.alias_manager')->getPathByAlias($path);
         // Look! We're using arg() in Drupal 8 because we have to.
-        $args = explode('/', $path);
+        $args = explode('/', $node_path);
         if (isset($args[$i])) {
           $entity = \Drupal::entityTypeManager()->getStorage($type)->load($args[$i]);
         }

**Comment by agentrickard** [comment]
That makes perfect sense. We should really write a test for this.

**Comment by agentrickard** [comment]
This has been added.
