### ISSUE TITLE
Add Functional tests to travis setup

### ISSUE THREAD

**Issue by agentrickard** [agentrickard/domain#288]
@zerolab 

I'm about to commit #282, which adds Functional testing. 

Any ideas how we add that to Travis? It involves setting up phpuinit config.

**Comment by zerolab** [comment]
Hi @agentrickard,

It should be as simple as adding `./vendor/bin/phpunit` to the `script:` part, probably after the other tests. I think it could use a `--group=Domain` part, but need to read more into it.

An alternative is to use https://github.com/LionsAd/drupal_ti which provides nicely packaged scripts and various runners. I've lots of modules using it to run tests on Travis.

Hope to get something in the next day or two

**Comment by zerolab** [comment]
Unrelated, the tests are currently failing with:

```
Parse error: syntax error, unexpected ')' in /home/travis/build/agentrickard/domain/domain_access/tests/src/Functional/DomainAccessElementTest.php on line 106
```

**Comment by agentrickard** [comment]
Sigh. Fixed that.

**Comment by zerolab** [comment]
We may not need to do much for the Functional testing. With the typo fixed, the tests are still failing, but with:

```
---- Drupal\Tests\domain_access\Functional\DomainAccessElementTest ----
Status    Group      Filename          Line Function                            
--------------------------------------------------------------------------------
Fail      Other      DomainAccessEleme   39 Drupal\Tests\domain_access\Function
    Failed asserting that false is true.
Fail      Other      phpunit-22.xml       0 Drupal\Tests\domain_access\Function
    PHPunit Test failed to complete; Error: PHPUnit 4.8.27 by Sebastian
    Bergmann and contributors.
    
    F
    
    Time: 44.56 seconds, Memory: 6.00Mb
    
    There was 1 failure:
    
    1)
    Drupal\Tests\domain_access\Functional\DomainAccessElementTest::testDomainAccessElement
    Node saved with three domain records.
    Failed asserting that false is true.
    
    /home/travis/build/agentrickard/drupal/core/tests/Drupal/KernelTests/AssertLegacyTrait.php:23
    /home/travis/build/agentrickard/domain/domain_access/tests/src/Functional/DomainAccessElementTest.php:129
    
    FAILURES!
    Tests: 1, Assertions: 15, Failures: 1.
The command "php core/scripts/run-tests.sh --verbose --color --concurrency 4 --php `which php` --url http://example.com:8080 domain_access" exited with 1.
```

So the test runner picks it up. Will need to confirm locally why the test fails

**Comment by agentrickard** [comment]
Bah. These were working yesterday.when I opened the issue.

**Comment by agentrickard** [comment]
Working now. Had to clear the node load cache.

**Comment by zerolab** [comment]
Fantastic!
If tests go green, I don't think there's anything else to do on this issue.

**Comment by agentrickard** [comment]
Do you have any insight about the fact that it works? 

This page -- https://www.drupal.org/docs/8/phpunit/phpunit-browser-test-tutorial -- suggests that we need a phpunit.xml file.

**Comment by zerolab** [comment]
Just got the notifications for this (currently travelling) I believe run-tests takes care of that as it runs the any BrowserTest tests
