### ISSUE TITLE
Domain id is based on hostname, which is not always unique

### ISSUE THREAD

**Issue by jurcello** [agentrickard/domain#297]
The domain id is now based on the hostname, which is not unique in all cases (for instance when using country_path):

public function createDomainId() {
    // We cannot reliably use sequences (1, 2, 3) because those can be different
    // across environments. Instead, we use the crc32 hash function to create a
    // unique numeric id for each domain. In some systems (Windows?) we have
    // reports of crc32 returning a negative number. Issue #2794047.
    $this->domain_id = abs((int) crc32($this->getHostname()));
  }

There are two possible ways to distinguish between domains: hostname or path prefix.
Although path prefix is suboptimal, there are use cases where it is needed.
When the domain id is based on the hostname this does not support path prefixes.
When the domain id is based on the id (which by definition should be unique) this problem is solved.

**Comment by agentrickard** [comment]
I've moved this work into #300. Thanks for the help!
