### ISSUE TITLE
Exception in Affiliated editors[affiliated_editors]

### ISSUE THREAD

**Issue by drupler** [agentrickard/domain#299]
While visiting `admin/content/domain-editors/$DOMAIN`, I am getting this error -

`Drupal\Core\Database\DatabaseExceptionWrapper: Exception in Affiliated editors[affiliated_editors]: SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'drupal.users_field_data.created' which is not in SELECT list; this is incompatible with DISTINCT: SELECT DISTINCT users_field_data.uid AS uid FROM {users_field_data} users_field_data LEFT JOIN {user__field_domain_access} user__field_domain_access ON users_field_data.uid = user__field_domain_access.entity_id AND (user__field_domain_access.deleted = :views_join_condition_0 AND user__field_domain_access.langcode = users_field_data.langcode) WHERE (( (user__field_domain_access.field_domain_access_target_id = :db_condition_placeholder_2) )AND(( (users_field_data.default_langcode = :db_condition_placeholder_3) AND (users_field_data.uid != :db_condition_placeholder_4) ))) ORDER BY users_field_data.created DESC LIMIT 50 OFFSET 0; Array ( [:db_condition_placeholder_2] => gehanhomes [:db_condition_placeholder_3] => 1 [:db_condition_placeholder_4] => 0 [:views_join_condition_0] => 0 ) in Drupal\views\Plugin\views\query\Sql->execute() (line 1452 of $DOCROOT/core/modules/views/src/Plugin/views/query/Sql.php).`

**Comment by agentrickard** [comment]
I cannot replicate this error using the 8,.x-1.x branch and Drupal core 8.2.

Have you edited the View (affiliated_editors) at all? Because the error suggests that the "Created" field (shown in the view as "Member for") has been removed.
