### ISSUE TITLE
Use subfolder as domain selector

### ISSUE THREAD

**Issue by heyyoyo** [agentrickard/domain#307]
In Drupal 7, only domain name and subdomain were possible for each domain.
Do you have any plan to also support domain as subdirectory ?
Like:
- www.mydns.com/subdirectory1 - domain A 
- www.mydns.com/subdirectory2 - domain B
- www.mydns.com/subdirectory3 - domain C...

**Comment by agentrickard** [comment]
I think this has already been done in the Country Path module.

https://www.drupal.org/project/country_path

See https://www.drupal.org/node/2833053.
