### ISSUE TITLE
Update issue in Domain Alpha module

### ISSUE THREAD

**Issue by nedjo** [agentrickard/domain#310]
The Domain Alpha module contains a (much appreciated!) update needed for sites updating from a previous release. However, since this module is not yet installed on those sites, the update won't run. (On install, the `domain_alpha` schema value will be set to that of the update.) Needed:

* Copy the code from the `domain_alpha_update_8001()` update into `hook_install()`.

A workaround is:

* Enable Domain Alpha.
* Enable Devel.
* Paste in content of `domain_alpha_update_8001()` from `domain_alpha.info.yml` to form at /devel/php and submit.

**Comment by agentrickard** [comment]
Sigh. Good point.
