### ISSUE TITLE
Moving to Drupal 8.3

### ISSUE THREAD

**Issue by agentrickard** [agentrickard/domain#322]
Just a note that I'm going to start doing base development against the 8.3 branch, up from 8.2.

Tests will still run on 8.2 and 8.3.

**Comment by agentrickard** [comment]
And I found one failing test as a result of changes to core.

https://www.drupal.org/node/2849894

See #323

**Comment by andypost** [comment]
Filed #334 
also https://www.drupal.org/node/2849874 supposes to get rid of `count($storage->loadMultiple())` in favour of count queries like #332 started
