### ISSUE TITLE
Domain Conf is broken

### ISSUE THREAD

**Issue by agentrickard** [agentrickard/domain#33]
DomainConfigOverriderTest fail:

 	Completion check 	DomainConfigOverriderTest.php 	20 	Drupal\domain_config\Tests\DomainConfigOverriderTest->testDomainConfigOverrider() 	Fail
Drupal\Core\Config\Schema\SchemaIncompleteException: No schema for domain.config.one_example_com.system.site in Drupal\Core\Config\Testing\ConfigSchemaChecker->onConfigSave() (line 91 of /Applications/MAMP/htdocs/drupal-8/core/lib/Drupal/Core/Config/Testing/ConfigSchemaChecker.php).

**Comment by agentrickard** [comment]
A whole bunch of code is sitting in branch *33-domain-config* and needs extensive testing.

**Comment by agentrickard** [comment]
Current status:

* The original tests are in the 8.0.x branch and no longer work. https://github.com/agentrickard/domain/tree/8.0.x
* Attempts to fix the issue are in the *33-domain-config* branch and need testing. https://github.com/agentrickard/domain/tree/33-domain-config

**Comment by mtift** [comment]
With https://www.drupal.org/node/2432791, you'll need to do something like this in your save() implementation:

```
  public function save($has_trusted_data = FALSE) {
    if (!$has_trusted_data) {
      foreach ($this->data as $key => $value) {
        $this->validateValue($key, $value);
      }
    }
```

So then it looks like there is just something going on with `$this->assertText('Test default site name');`.

Was this issue just about DomainConfigOverrideImportTest, or was there more to it than that?

**Comment by agentrickard** [comment]
The issue is about the tests in DomainConfigOverrideImportTest failing, yes. That's the indicator that something isn't behaving. But a host of errors seem to derive from https://www.drupal.org/node/2391795. If I don't disable strict config checking, I get fatal errors.

The documentation on https://www.drupal.org/node/1928898 is new to me, so perhaps the task here is to  make this code conform to that and fix any documentation along the way.

**Comment by agentrickard** [comment]
See LanguageConfigFactoryOverride.php and https://www.drupal.org/node/1928898
