### ISSUE TITLE
Move DomainCreator & DomainLoader code to DomainStorage

### ISSUE THREAD

**Issue by andypost** [agentrickard/domain#334]
Core using storage handler for this sort of functions
See example in `\Drupal\taxonomy\VocabularyStorage::getToplevelTids()`

Proposal is to introduce `DomainStorageInterface` to document required methods

**Comment by andypost** [comment]
https://www.drupal.org/node/2245849

**Comment by agentrickard** [comment]
Makes sense from a semantic point of view. Fairly low priority. though.

Would we bother marking the old DomainLoader as @deprecated and keeping support for it? There are certainly modules in the wild that use that class.

**Comment by andypost** [comment]
Yep, we should keep BC only for interface

**Comment by agentrickard** [comment]
I tried to spin this up and am stuck on an implementation point.

See https://github.com/agentrickard/domain/tree/334-domain-storage

* I assume that DomainStorage should extend ConfigEntityStorage
* That class is not a service. 
* I've been using DomnainLoader as a service (for convenience)
* I also see that we can remove the DomainCreator service, because that is covered by Storage.

Right now, this branch fails since we cannot inject the $entity_type into the DomainStorage service.

So do we need to remove the new `domain.storage` service and instead load from the entity type manager? 

Should we spin up a lightweight service that simply loads the domain storage instance from the entity type manager?

I'm looking for some best practices here.

**Comment by agentrickard** [comment]
I went with removing domain.storage as a service and using the entity_type.manager service instead. Probably a lot of clean up to do.

**Comment by andypost** [comment]
Changes in the branch looks exactly what I mean in the issue
- https://github.com/agentrickard/domain/commit/6bb38c9a8e65b06b856369d8db66fc563257efbd this makes much more inline as core works

> So do we need to remove the new domain.storage service and instead load from the entity type manager?

Yes, having special storage service is most common!

> Should we spin up a lightweight service that simply loads the domain storage instance from the entity type manager?

I see no reason in the mediator, most of contrib/integration code injects ETM anyway so they will get domain storage as any other entity storage & proper interface will help to type hint its methods.

PS: Thinking about special service better to create 'CurrentDomain` service like core provides `current_user` proxy & commerce have https://github.com/drupalcommerce/commerce/blob/8.x-2.x/modules/store/src/CurrentStore.php

**Comment by andypost** [comment]
Checked 
- https://github.com/skilld-labs/domain_entity/blob/8.x-1.x/domain_entity.services.yml
- https://github.com/skilld-labs/domain_block_content/blob/8.x-1.x/domain_block_content.services.yml
- https://github.com/skilld-labs/domain_menu_access/blob/8.x/domain_menu_access.services.yml

Found only one usage in https://github.com/skilld-labs/domain_language/blob/master/src/DomainLanguagesServiceProvider.php

**Comment by agentrickard** [comment]
I don't quite understand this comment:

* `Yes, having special storage service is most common!`

From my tests, we cannot make the DomainStorage plugin class a service, because it requires an EntityType object that cannot be injected. Do you mean `storage plugin` here?

* Another question, we're loading the EntityTypeManager but in most cases discarding it and just setting the domainStorage plugin. See DomainNegotiator::__construct() for instance:

```
$this->domainStorage = $entity_type_manager->getStorage('domain');
```

Should we retain the $entity_type_manager as a property?


As to DomainCurrent, you can already grab that from the DomainNegotiator service, so I'm not sure how that helps.

**Comment by andypost** [comment]
> we're loading the EntityTypeManager
As I remember there was suggestion to pass ETM into static createInstance() to easy mock and test usage of method calls to ETM, but __construct() should accept entity storage handler (the `DomainStorageInterface` in this case)

Then everywhere in code classes defines dependency on ETM to extract domainstorage

> Should we retain the $entity_type_manager as a property?
Yes, because `\Drupal\Core\Entity\EntityHandlerInterface::createInstance()` dictates but `__construct` is implementation details that internal to `DomainStorageInterface`

**Comment by agentrickard** [comment]
So something like this, from DomainListBuilder:

```
  /**
   * {@inheritdoc}
   */
  public static function createInstance(ContainerInterface $container, EntityTypeInterface $entity_type) {
    return new static(
      $entity_type,
      $container->get('entity_type.manager')->getStorage('domain'),
      $container->get('current_user'),
      $container->get('redirect.destination'),
      $container->get('entity_type.manager'),
      $container->get('module_handler'),
      $container->get('domain.element_manager')
    );
  }

  /**
   * Constructs a new EntityListBuilder object.
   *
   * @param \Drupal\Core\Entity\EntityTypeInterface $entity_type
   *   The entity type definition.
   * @param \Drupal\domain\DomainStorageInterface $storage
   *   The entity storage class.
   * @param \Drupal\Core\Session\AccountInterface $account
   *   The active user account.
   * @param \Drupal\Core\Routing\RedirectDestinationInterface $destination
   *   The redirect destination helper.
   * @param \Drupal\Core\Entity\EntityTypeManagerInterface $entity_type_manager
   *   The entity type manager.
   * @param \Drupal\Core\Extension\ModuleHandlerInterface $module_handler
   *   The module handler.
   * @param \Drupal\domain\DomainElementManager $domain_element_manager
   *   The domain field element manager.
   */
  public function __construct(EntityTypeInterface $entity_type, DomainStorageInterface $storage, AccountInterface $account, RedirectDestinationInterface $destination_handler, EntityTypeManagerInterface $entity_type_manager, ModuleHandlerInterface $module_handler, DomainElementManager $domain_element_manager) {
    parent::__construct($entity_type, $storage);
    $this->entityTypeId = $entity_type->id();
    $this->domainStorage = $storage;
    $this->entityType = $entity_type;
    $this->currentUser = $account;
    $this->destinationHandler = $destination_handler;
    $this->entityTypeManager = $entity_type_manager;
    $this->accessHandler = $this->entityTypeManager->getAccessControlHandler('domain');
    $this->moduleHandler = $module_handler;
    $this->domainElementManager = $domain_element_manager;
    $this->userStorage = $this->entityTypeManager->getStorage('user');
  }

```

**Comment by andypost** [comment]
Yes, exactly the same approach

**Comment by agentrickard** [comment]
I _think_ this is done. I also moved the DomainAliasLoader.

https://github.com/agentrickard/domain/pull/377

The only remaining question is -- how to update module authors so they change their code/
