### ISSUE TITLE
Installing Domain Configuration Module kills my site

### ISSUE THREAD

**Issue by erok415** [agentrickard/domain#338]
Each time I try to install the domain configuration module, my site breaks. What the animated gif below to see what happens. Here is the error code `Fatal error: Call to a member function getRequestUri() on a non-object in /srv/bindings/8dc2042b091648d8ba8d1f699b3de16a/code/modules/domain/domain/src/Entity/Domain.php on line 286 `
You can also see what domain modules I currently have installed too.

![2017-02-17 21 52 55](https://cloud.githubusercontent.com/assets/8429801/23090801/8a37b2de-f55b-11e6-9a56-8719da6a648f.gif)

**Comment by erok415** [comment]
Essentially, I'd like to add a frontpage for a new sub-domain and while I've tried to import a simple configuration entry 
`name: 'My Domain'
page:
  front: /page`
I'm getting an error due to a dependency.

**Comment by agentrickard** [comment]
Weird.

Do you have any domains configured before enabling that module?

**Comment by agentrickard** [comment]
What version of Drupal are you using? I'm not seeing the same issue in 8.3, and I've never run into this.

**Comment by erok415** [comment]
Hi There,
Yes, we are using Drupal 8.2.6. Yes, I had two domains configured before installing Domain Config.

I just now tried installing domain config in a DEV instance and I got this message Fatal error: Call to a member function getRequestUri() on a non-object in /code/modules/domain/domain/src/Entity/Domain.php on line 286
Erik

**Comment by agentrickard** [comment]
Odd. I'm not seeing that on 8.3 and it doesn't come up in our tests.

I wonder why /Drupal::request() would return nothing. If you can figure that out, we can solve this pretty easily.

**Comment by erok415** [comment]
Sorry, how would I go about doing that.
Erik

**Comment by agentrickard** [comment]
Normally by putting some debugging statements in the method and watching the results.

**Comment by erok415** [comment]
Ah, of course. I’m trying something now. I’ll let you know the results.
Erik
 <https://www.linkedin.com/pub/erik-cochran/44/795/87b>

**Comment by erok415** [comment]
Do you have an idea of when the UI for domain config will be released?
Erik
 <https://www.linkedin.com/pub/erik-cochran/44/795/87b>

**Comment by agentrickard** [comment]
No. There is an experimental branch that I haven't had time to test.

See https://github.com/agentrickard/domain/pull/294

**Comment by erok415** [comment]
I see.
 <https://www.linkedin.com/pub/erik-cochran/44/795/87b>

**Comment by erok415** [comment]
Hi again,
I think that I may be chasing the wrong thing. I want to debug, and it turns out that I’m debugging already: 
Enable debugging

You enable Twig Debugging in sites/default/services.yml.
(If services.yml does not yet exist; copy default.services.yml and copy it to services.yml.)

Set the debug variable to true.

parameters:
  twig.config:
    debug: true 
If you are using Firebug (in Firefox) make sure that "Show Comments" is enabled or view page source directly:

###

Is there another way that I should debug to figure this out? I seem to not be able to install Domain Config (while all other Domain modules are installed) without getting this error: Fatal error: Call to a member function getRequestUri() on a non-object in /code/modules/domain/domain/src/Entity/Domain.php on line 286

Looking for your direction.
Erik

**Comment by agentrickard** [comment]
We're not debugging Twig templates, so that isn't relevant. 

The question is "why does /Drupal::request() not return an object?"

Try replacing these lines in the Domain.php file:

```
  /**
   * {@inheritdoc}
   */
  public function setUrl() {
    $uri = \Drupal::request()->getRequestUri();
    $this->url = $this->getScheme() . $this->getHostname() . $uri;
  }
```

To:

```
  /**
   * {@inheritdoc}
   */
  public function setUrl() {
    $request = \Drupal::request();
    if (is_object($request)) {
      $uri = \Drupal::request()->getRequestUri();
      $this->url = $this->getScheme() . $this->getHostname() . $uri;
   }
  else {
    // Only include the next line if DEVEL and KINT are enabled.
    kint($request);
    $this->url = $this->getScheme() . $this->getHostname();
   }
  }
```

**Comment by erok415** [comment]
Sorry, where is that file located?
 <https://www.linkedin.com/pub/erik-cochran/44/795/87b>

**Comment by erok415** [comment]
Found it.
 <https://www.linkedin.com/pub/erik-cochran/44/795/87b>

**Comment by erok415** [comment]
I bet we’re close. But I’m a little new to kint and Drupal 8. I received this error after applying your code, running cc all, and trying to install Domain Config module. 

Fatal error: Call to undefined function Drupal\domain\Entity\kint() in /modules/domain/domain/src/Entity/Domain.php on line 301 

I truly appreciate your help. Could I pay you to jump on a zoom with me? Open source is great, but someones gotta get paid.
Erik



 <https://www.linkedin.com/pub/erik-cochran/44/795/87b>

**Comment by erok415** [comment]
Hi there,
I can confirm that Flexslider definitely conflicts with the domain module. I've successfully uninstalled and removed the Flexslider module. Once I did this, I was able to install Domain Config without error and import two records to set the homepage for each.
Then I tried installing Flexslider and that's when I received this: `Fatal error: Call to undefined function Drupal\domain\Entity\kint() in /modules/domain/domain/src/Entity/Domain.php on line 301 `

Erik

**Comment by zerolab** [comment]
Erik,

you need to download the [Devel](https://www.drupal.org/project/devel) module(s) and enable Kint, for the `kint()` function calls to work.

Cheers,
Dan

**Comment by erok415** [comment]
Hi There,
So I’ve removed any redirects and domain redirects that would affect the homepage or <front> for domaincon.mollyduggan.io <http://domaincon.mollyduggan.io/>. I cleared cache and I’m still getting the error "Redirects to external URLs are not allowed by default, use \Drupal\Core\Routing\TrustedRedirectResponse for it.” when I visit domconcar.mollyduggan.io/home <http://domconcar.mollyduggan.io/home>. This page belongs to the domain domaincon.mollyduggan.io <http://domaincon.mollyduggan.io/> and the domain module should change the subdomain to match the domain it belongs to which is domaincon. But the trusted host settings seems to not be working. I don’t want to modify core or the file that relates to this unless it’s okay to modify them. What do you think?
Erik

**Comment by agentrickard** [comment]
I don't understand that report in the context of this thread.

**Comment by erok415** [comment]
Sorry, I've been trying to work with pantheon to also solve this since this affects trusted host settings.
Erik

**Comment by agentrickard** [comment]
That error message typically comes from the routing system / redirects. Note this section of the README:

Trusted host settings
------

If using the trusted host security setting in Drupal 8, be sure to add each domain
and alias to the pattern list. For example:

```
$settings['trusted_host_patterns'] = array(
  '^*\.example\.com$',
  '^myexample\.com$',
  '^localhost$',
);
```

I'm wondering what would be issuing that redirect. If Domain Alias issues a redirect, we use TrustedRidrectResponse.
