### ISSUE TITLE
Access the Content overview page

### ISSUE THREAD

**Issue by cristinallamas** [agentrickard/domain#340]
it seems that by enabling Domain module the permission _Access the Content overview page_ gets overridden and not allows my non-admin users to access the content administrator page even though the permission _Access the Content overview page_ is set to true.

**Comment by agentrickard** [comment]
There is nothing in Domain itself that would do that.  It certainly is not true for a base authenticated user role with no special permissions.

![screen shot 2017-03-12 at 3 43 23 pm](https://cloud.githubusercontent.com/assets/360988/23835268/a82e1490-073a-11e7-9f17-7239af63f8a3.png)

Are you using a submodule like Domain Content?
