### ISSUE TITLE
Non-static method Drupal\domain_access\DomainAccessManager::getAccessValues() should not be called statically in Drupal\domain_access\DomainAccessManager::getAccessValues()

### ISSUE THREAD

**Issue by jtkunley** [agentrickard/domain#342]
Happened when deleting a field from a content type. Any ideas?  (8.2.7 / alpha8) 

`Strict warning: Non-static method Drupal\domain_access\DomainAccessManager::getAccessValues() should not be called statically in Drupal\domain_access\DomainAccessManager::getAccessValues() (line 105 of modules\domain\domain_access\src\DomainAccessManager.php).
Drupal\domain_access\DomainAccessManager::getAccessValues() (Line: 105)
Drupal\domain_access\DomainAccessManager::getDefaultValue(Object, Object)
call_user_func('Drupal\domain_access\DomainAccessManager::getDefaultValue', Object, Object) (Line: 388)
Drupal\Core\Field\FieldConfigBase->getDefaultValue(Object) (Line: 180)
Drupal\Core\Field\FieldItemList->applyDefaultValue() (Line: 112)
Drupal\Core\Entity\ContentEntityStorageBase->initFieldValues(Object, Array) (Line: 88)
Drupal\Core\Entity\ContentEntityStorageBase->doCreate(Array) (Line: 184)
Drupal\Core\Entity\EntityStorageBase->create(Array) (Line: 299)
_field_create_entity_from_ids(Object) (Line: 1559)
Drupal\Core\Entity\Sql\SqlContentEntityStorage->readFieldItemsToPurge(Object, 10) (Line: 175)
Drupal\Core\Entity\ContentEntityStorageBase->purgeFieldData(Object, 10) (Line: 96)
field_purge_batch(10) (Line: 113)
Drupal\field_ui\Form\FieldConfigDeleteForm->submitForm(Array, Object)
call_user_func_array(Array, Array) (Line: 111)
Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object) (Line: 51)
Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object) (Line: 585)
Drupal\Core\Form\FormBuilder->processForm('field_config_delete_form', Array, Object) (Line: 314)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 74)
Drupal\Core\Controller\FormController->getContentResult(Object, Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 574)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
call_user_func_array(Object, Array) (Line: 144)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 64)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 99)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 78)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 50)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 652)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
Strict warning: Non-static method Drupal\domain_access\DomainAccessManager::getAccessValues() should not be called statically in Drupal\domain_access\DomainAccessManager::getAccessValues() (line 105 of modules\domain\domain_access\src\DomainAccessManager.php).
Drupal\domain_access\DomainAccessManager::getAccessValues() (Line: 105)
Drupal\domain_access\DomainAccessManager::getDefaultValue(Object, Object)
call_user_func('Drupal\domain_access\DomainAccessManager::getDefaultValue', Object, Object) (Line: 388)
Drupal\Core\Field\FieldConfigBase->getDefaultValue(Object) (Line: 180)
Drupal\Core\Field\FieldItemList->applyDefaultValue() (Line: 112)
Drupal\Core\Entity\ContentEntityStorageBase->initFieldValues(Object, Array) (Line: 88)
Drupal\Core\Entity\ContentEntityStorageBase->doCreate(Array) (Line: 184)
Drupal\Core\Entity\EntityStorageBase->create(Array) (Line: 299)
_field_create_entity_from_ids(Object) (Line: 1559)
Drupal\Core\Entity\Sql\SqlContentEntityStorage->readFieldItemsToPurge(Object, 9) (Line: 175)
Drupal\Core\Entity\ContentEntityStorageBase->purgeFieldData(Object, 9) (Line: 96)
field_purge_batch(10) (Line: 113)
Drupal\field_ui\Form\FieldConfigDeleteForm->submitForm(Array, Object)
call_user_func_array(Array, Array) (Line: 111)
Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object) (Line: 51)
Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object) (Line: 585)
Drupal\Core\Form\FormBuilder->processForm('field_config_delete_form', Array, Object) (Line: 314)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 74)
Drupal\Core\Controller\FormController->getContentResult(Object, Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 574)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
call_user_func_array(Object, Array) (Line: 144)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 64)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 99)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 78)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 50)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 652)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)`

**Comment by agentrickard** [comment]
This is, I think, filed on d.o., too, but I was never able to replicate.

**Comment by agentrickard** [comment]
I still can't replicate this. 

What type of field were you deleting? How was it created?
