### ISSUE TITLE
Looking for patch to make Domain Access work together with Content Access or Permissions by Term

### ISSUE THREAD

**Issue by FranDevos** [agentrickard/domain#350]
I need to find a way to restrict certain content on one subdomain to a certain role but both Content Access and Permissions by Term break the Domain Access module. When installed and permissions are rebuilt, all content is published on all domains, including all content that was domain-specific before installing one of those modules.

Is there a way to be able to use one of these modules to restrict certain content to a user role on one subdomain?

Thanks!

**Comment by zerolab** [comment]
You can try https://www.drupal.org/project/acb -- we ported the D7 version to work with Domain Access

**Comment by FranDevos** [comment]
I'll have to try and figure this one out when I have some more time on my hands because when I install ACB & Content Access, the anonymous user does not see anything on the site anymore exept for the contact page. I tried changing permissions, rebuilding permissions, but it does not seem to work. Will get back to this asap, next week at the latest!

**Comment by FranDevos** [comment]
No luck so far. It seems like Content Access now hides everything for anonymous users. ACB should just work out of the box? Is there something I'm missing here? I configured several content types to be visible with Content Access for anonymous users but no luck.

**Comment by zerolab** [comment]
Add an issue to the ACB module queue?

This is not enough information for anyone to debug remotely. When you create the ACB issue please provide as much context as possible.

I think this issue can be closed as it not related to Domain Access as such.
