### ISSUE TITLE
Domain environment switch

### ISSUE THREAD

**Issue by jestinijames** [agentrickard/domain#354]
Hi, 
So I have 10 domains on my site. So I created 10 records. 
example: www.example.com
But each of these domains have different environments. like sandbox, production, uat etc
What I want is:
If I am on any of the above environments, the domain automatically should change:
example: sbox.example.com
               prod.example.com
etc

Initially I tried adding every single url into the domain. This was bad as building the vm took over 2 hours and if i have to add content and select which domain to add it to, there was over 200 to look over. 

Can you suggest a better option please? or is there some code to change it in the domain configurations based on the url change. If there is a code to change it, then it would be awesome.

Thanks

**Comment by agentrickard** [comment]
You want to use Domain Alias to set up the environments. 

See the Development Workflow section of https://github.com/agentrickard/domain/blob/8.x-1.x/domain_alias/README.md
