### ISSUE TITLE
Node Access duplicate issue...

### ISSUE THREAD

**Issue by puogintas** [agentrickard/domain#371]
Hi All,

First of all thanks for doing amazing work with Domain porting to Drupal 8 but recently I came across an issue that may be related to you guys.... Although I am not sure... Essentially now if I want to select more than 1 domain (on domain access I get this error):

`Drupal\Core\Entity\EntityStorageException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1266-2147483647-domain_id-en' for key 'PRIMARY': INSERT INTO {node_access} (nid, langcode, fallback, realm, gid, grant_view, grant_update, grant_delete) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6, :db_insert_placeholder_7), (:db_insert_placeholder_8, :db_insert_placeholder_9, :db_insert_placeholder_10, :db_insert_placeholder_11, :db_insert_placeholder_12, :db_insert_placeholder_13, :db_insert_placeholder_14, :db_insert_placeholder_15), (:db_insert_placeholder_16, :db_insert_placeholder_17, :db_insert_placeholder_18, :db_insert_placeholder_19, :db_insert_placeholder_20, :db_insert_placeholder_21, :db_insert_placeholder_22, :db_insert_placeholder_23), (:db_insert_placeholder_24, :db_insert_placeholder_25, :db_insert_placeholder_26, :db_insert_placeholder_27, :db_insert_placeholder_28, :db_insert_placeholder_29, :db_insert_placeholder_30, :db_insert_placeholder_31), (:db_insert_placeholder_32, :db_insert_placeholder_33, :db_insert_placeholder_34, :db_insert_placeholder_35, :db_insert_placeholder_36, :db_insert_placeholder_37, :db_insert_placeholder_38, :db_insert_placeholder_39), (:db_insert_placeholder_40, :db_insert_placeholder_41, :db_insert_placeholder_42, :db_insert_placeholder_43, :db_insert_placeholder_44, :db_insert_placeholder_45, :db_insert_placeholder_46, :db_insert_placeholder_47), (:db_insert_placeholder_48, :db_insert_placeholder_49, :db_insert_placeholder_50, :db_insert_placeholder_51, :db_insert_placeholder_52, :db_insert_placeholder_53, :db_insert_placeholder_54, :db_insert_placeholder_55), (:db_insert_placeholder_56, :db_insert_placeholder_57, :db_insert_placeholder_58, :db_insert_placeholder_59, :db_insert_placeholder_60, :db_insert_placeholder_61, :db_insert_placeholder_62, :db_insert_placeholder_63), (:db_insert_placeholder_64, :db_insert_placeholder_65, :db_insert_placeholder_66, :db_insert_placeholder_67, :db_insert_placeholder_68, :db_insert_placeholder_69, :db_insert_placeholder_70, :db_insert_placeholder_71), (:db_insert_placeholder_72, :db_insert_placeholder_73, :db_insert_placeholder_74, :db_insert_placeholder_75, :db_insert_placeholder_76, :db_insert_placeholder_77, :db_insert_placeholder_78, :db_insert_placeholder_79), (:db_insert_placeholder_80, :db_insert_placeholder_81, :db_insert_placeholder_82, :db_insert_placeholder_83, :db_insert_placeholder_84, :db_insert_placeholder_85, :db_insert_placeholder_86, :db_insert_placeholder_87), (:db_insert_placeholder_88, :db_insert_placeholder_89, :db_insert_placeholder_90, :db_insert_placeholder_91, :db_insert_placeholder_92, :db_insert_placeholder_93, :db_insert_placeholder_94, :db_insert_placeholder_95), (:db_insert_placeholder_96, :db_insert_placeholder_97, :db_insert_placeholder_98, :db_insert_placeholder_99, :db_insert_placeholder_100, :db_insert_placeholder_101, :db_insert_placeholder_102, :db_insert_placeholder_103), (:db_insert_placeholder_104, :db_insert_placeholder_105, :db_insert_placeholder_106, :db_insert_placeholder_107, :db_insert_placeholder_108, :db_insert_placeholder_109, :db_insert_placeholder_110, :db_insert_placeholder_111), (:db_insert_placeholder_112, :db_insert_placeholder_113, :db_insert_placeholder_114, :db_insert_placeholder_115, :db_insert_placeholder_116, :db_insert_placeholder_117, :db_insert_placeholder_118, :db_insert_placeholder_119), (:db_insert_placeholder_120, :db_insert_placeholder_121, :db_insert_placeholder_122, :db_insert_placeholder_123, :db_insert_placeholder_124, :db_insert_placeholder_125, :db_insert_placeholder_126, :db_insert_placeholder_127), (:db_insert_placeholder_128, :db_insert_placeholder_129, :db_insert_placeholder_130, :db_insert_placeholder_131, :db_insert_placeholder_132, :db_insert_placeholder_133, :db_insert_placeholder_134, :db_insert_placeholder_135), (:db_insert_placeholder_136, :db_insert_placeholder_137, :db_insert_placeholder_138, :db_insert_placeholder_139, :db_insert_placeholder_140, :db_insert_placeholder_141, :db_insert_placeholder_142, :db_insert_placeholder_143), (:db_insert_placeholder_144, :db_insert_placeholder_145, :db_insert_placeholder_146, :db_insert_placeholder_147, :db_insert_placeholder_148, :db_insert_placeholder_149, :db_insert_placeholder_150, :db_insert_placeholder_151), (:db_insert_placeholder_152, :db_insert_placeholder_153, :db_insert_placeholder_154, :db_insert_placeholder_155, :db_insert_placeholder_156, :db_insert_placeholder_157, :db_insert_placeholder_158, :db_insert_placeholder_159), (:db_insert_placeholder_160, :db_insert_placeholder_161, :db_insert_placeholder_162, :db_insert_placeholder_163, :db_insert_placeholder_164, :db_insert_placeholder_165, :db_insert_placeholder_166, :db_insert_placeholder_167), (:db_insert_placeholder_168, :db_insert_placeholder_169, :db_insert_placeholder_170, :db_insert_placeholder_171, :db_insert_placeholder_172, :db_insert_placeholder_173, :db_insert_placeholder_174, :db_insert_placeholder_175), (:db_insert_placeholder_176, :db_insert_placeholder_177, :db_insert_placeholder_178, :db_insert_placeholder_179, :db_insert_placeholder_180, :db_insert_placeholder_181, :db_insert_placeholder_182, :db_insert_placeholder_183), (:db_insert_placeholder_184, :db_insert_placeholder_185, :db_insert_placeholder_186, :db_insert_placeholder_187, :db_insert_placeholder_188, :db_insert_placeholder_189, :db_insert_placeholder_190, :db_insert_placeholder_191), (:db_insert_placeholder_192, :db_insert_placeholder_193, :db_insert_placeholder_194, :db_insert_placeholder_195, :db_insert_placeholder_196, :db_insert_placeholder_197, :db_insert_placeholder_198, :db_insert_placeholder_199), (:db_insert_placeholder_200, :db_insert_placeholder_201, :db_insert_placeholder_202, :db_insert_placeholder_203, :db_insert_placeholder_204, :db_insert_placeholder_205, :db_insert_placeholder_206, :db_insert_placeholder_207), (:db_insert_placeholder_208, :db_insert_placeholder_209, :db_insert_placeholder_210, :db_insert_placeholder_211, :db_insert_placeholder_212, :db_insert_placeholder_213, :db_insert_placeholder_214, :db_insert_placeholder_215), (:db_insert_placeholder_216, :db_insert_placeholder_217, :db_insert_placeholder_218, :db_insert_placeholder_219, :db_insert_placeholder_220, :db_insert_placeholder_221, :db_insert_placeholder_222, :db_insert_placeholder_223), (:db_insert_placeholder_224, :db_insert_placeholder_225, :db_insert_placeholder_226, :db_insert_placeholder_227, :db_insert_placeholder_228, :db_insert_placeholder_229, :db_insert_placeholder_230, :db_insert_placeholder_231), (:db_insert_placeholder_232, :db_insert_placeholder_233, :db_insert_placeholder_234, :db_insert_placeholder_235, :db_insert_placeholder_236, :db_insert_placeholder_237, :db_insert_placeholder_238, :db_insert_placeholder_239); Array ( [:db_insert_placeholder_0] => 1266 [:db_insert_placeholder_1] => en [:db_insert_placeholder_2] => 1 [:db_insert_placeholder_3] => domain_id [:db_insert_placeholder_4] => 2147483647 [:db_insert_placeholder_5] => 1 [:db_insert_placeholder_6] => 1 [:db_insert_placeholder_7] => 1 [:db_insert_placeholder_8] => 1266 [:db_insert_placeholder_9] => en [:db_insert_placeholder_10] => 1 [:db_insert_placeholder_11] => domain_id [:db_insert_placeholder_12] => 1528372610 [:db_insert_placeholder_13] => 1 [:db_insert_placeholder_14] => 1 [:db_insert_placeholder_15] => 1 [:db_insert_placeholder_16] => 1266 [:db_insert_placeholder_17] => en [:db_insert_placeholder_18] => 1 [:db_insert_placeholder_19] => domain_id [:db_insert_placeholder_20] => 2147483647 [:db_insert_placeholder_21] => 1 [:db_insert_placeholder_22] => 1 [:db_insert_placeholder_23] => 1 [:db_insert_placeholder_24] => 1266 [:db_insert_placeholder_25] => en [:db_insert_placeholder_26] => 1 [:db_insert_placeholder_27] => domain_id [:db_insert_placeholder_28] => 2147483647 [:db_insert_placeholder_29] => 1 [:db_insert_placeholder_30] => 1 [:db_insert_placeholder_31] => 1 [:db_insert_placeholder_32] => 1266 [:db_insert_placeholder_33] => en [:db_insert_placeholder_34] => 1 [:db_insert_placeholder_35] => domain_id [:db_insert_placeholder_36] => 2147483647 [:db_insert_placeholder_37] => 1 [:db_insert_placeholder_38] => 1 [:db_insert_placeholder_39] => 1 [:db_insert_placeholder_40] => 1266 [:db_insert_placeholder_41] => en [:db_insert_placeholder_42] => 1 [:db_insert_placeholder_43] => domain_site [:db_insert_placeholder_44] => 0 [:db_insert_placeholder_45] => 1 [:db_insert_placeholder_46] => 0 [:db_insert_placeholder_47] => 0 [:db_insert_placeholder_48] => 1266 [:db_insert_placeholder_49] => de [:db_insert_placeholder_50] => 0 [:db_insert_placeholder_51] => domain_id [:db_insert_placeholder_52] => 2147483647 [:db_insert_placeholder_53] => 1 [:db_insert_placeholder_54] => 1 [:db_insert_placeholder_55] => 1 [:db_insert_placeholder_56] => 1266 [:db_insert_placeholder_57] => de [:db_insert_placeholder_58] => 0 [:db_insert_placeholder_59] => domain_id [:db_insert_placeholder_60] => 1528372610 [:db_insert_placeholder_61] => 1 [:db_insert_placeholder_62] => 1 [:db_insert_placeholder_63] => 1 [:db_insert_placeholder_64] => 1266 [:db_insert_placeholder_65] => de [:db_insert_placeholder_66] => 0 [:db_insert_placeholder_67] => domain_id [:db_insert_placeholder_68] => 2147483647 [:db_insert_placeholder_69] => 1 [:db_insert_placeholder_70] => 1 [:db_insert_placeholder_71] => 1 [:db_insert_placeholder_72] => 1266 [:db_insert_placeholder_73] => de [:db_insert_placeholder_74] => 0 [:db_insert_placeholder_75] => domain_id [:db_insert_placeholder_76] => 2147483647 [:db_insert_placeholder_77] => 1 [:db_insert_placeholder_78] => 1 [:db_insert_placeholder_79] => 1 [:db_insert_placeholder_80] => 1266 [:db_insert_placeholder_81] => de [:db_insert_placeholder_82] => 0 [:db_insert_placeholder_83] => domain_id [:db_insert_placeholder_84] => 2147483647 [:db_insert_placeholder_85] => 1 [:db_insert_placeholder_86] => 1 [:db_insert_placeholder_87] => 1 [:db_insert_placeholder_88] => 1266 [:db_insert_placeholder_89] => de [:db_insert_placeholder_90] => 0 [:db_insert_placeholder_91] => domain_site [:db_insert_placeholder_92] => 0 [:db_insert_placeholder_93] => 1 [:db_insert_placeholder_94] => 0 [:db_insert_placeholder_95] => 0 [:db_insert_placeholder_96] => 1266 [:db_insert_placeholder_97] => fr [:db_insert_placeholder_98] => 0 [:db_insert_placeholder_99] => domain_id [:db_insert_placeholder_100] => 2147483647 [:db_insert_placeholder_101] => 1 [:db_insert_placeholder_102] => 1 [:db_insert_placeholder_103] => 1 [:db_insert_placeholder_104] => 1266 [:db_insert_placeholder_105] => fr [:db_insert_placeholder_106] => 0 [:db_insert_placeholder_107] => domain_id [:db_insert_placeholder_108] => 1528372610 [:db_insert_placeholder_109] => 1 [:db_insert_placeholder_110] => 1 [:db_insert_placeholder_111] => 1 [:db_insert_placeholder_112] => 1266 [:db_insert_placeholder_113] => fr [:db_insert_placeholder_114] => 0 [:db_insert_placeholder_115] => domain_id [:db_insert_placeholder_116] => 2147483647 [:db_insert_placeholder_117] => 1 [:db_insert_placeholder_118] => 1 [:db_insert_placeholder_119] => 1 [:db_insert_placeholder_120] => 1266 [:db_insert_placeholder_121] => fr [:db_insert_placeholder_122] => 0 [:db_insert_placeholder_123] => domain_id [:db_insert_placeholder_124] => 2147483647 [:db_insert_placeholder_125] => 1 [:db_insert_placeholder_126] => 1 [:db_insert_placeholder_127] => 1 [:db_insert_placeholder_128] => 1266 [:db_insert_placeholder_129] => fr [:db_insert_placeholder_130] => 0 [:db_insert_placeholder_131] => domain_id [:db_insert_placeholder_132] => 2147483647 [:db_insert_placeholder_133] => 1 [:db_insert_placeholder_134] => 1 [:db_insert_placeholder_135] => 1 [:db_insert_placeholder_136] => 1266 [:db_insert_placeholder_137] => fr [:db_insert_placeholder_138] => 0 [:db_insert_placeholder_139] => domain_site [:db_insert_placeholder_140] => 0 [:db_insert_placeholder_141] => 1 [:db_insert_placeholder_142] => 0 [:db_insert_placeholder_143] => 0 [:db_insert_placeholder_144] => 1266 [:db_insert_placeholder_145] => es [:db_insert_placeholder_146] => 0 [:db_insert_placeholder_147] => domain_id [:db_insert_placeholder_148] => 2147483647 [:db_insert_placeholder_149] => 1 [:db_insert_placeholder_150] => 1 [:db_insert_placeholder_151] => 1 [:db_insert_placeholder_152] => 1266 [:db_insert_placeholder_153] => es [:db_insert_placeholder_154] => 0 [:db_insert_placeholder_155] => domain_id [:db_insert_placeholder_156] => 1528372610 [:db_insert_placeholder_157] => 1 [:db_insert_placeholder_158] => 1 [:db_insert_placeholder_159] => 1 [:db_insert_placeholder_160] => 1266 [:db_insert_placeholder_161] => es [:db_insert_placeholder_162] => 0 [:db_insert_placeholder_163] => domain_id [:db_insert_placeholder_164] => 2147483647 [:db_insert_placeholder_165] => 1 [:db_insert_placeholder_166] => 1 [:db_insert_placeholder_167] => 1 [:db_insert_placeholder_168] => 1266 [:db_insert_placeholder_169] => es [:db_insert_placeholder_170] => 0 [:db_insert_placeholder_171] => domain_id [:db_insert_placeholder_172] => 2147483647 [:db_insert_placeholder_173] => 1 [:db_insert_placeholder_174] => 1 [:db_insert_placeholder_175] => 1 [:db_insert_placeholder_176] => 1266 [:db_insert_placeholder_177] => es [:db_insert_placeholder_178] => 0 [:db_insert_placeholder_179] => domain_id [:db_insert_placeholder_180] => 2147483647 [:db_insert_placeholder_181] => 1 [:db_insert_placeholder_182] => 1 [:db_insert_placeholder_183] => 1 [:db_insert_placeholder_184] => 1266 [:db_insert_placeholder_185] => es [:db_insert_placeholder_186] => 0 [:db_insert_placeholder_187] => domain_site [:db_insert_placeholder_188] => 0 [:db_insert_placeholder_189] => 1 [:db_insert_placeholder_190] => 0 [:db_insert_placeholder_191] => 0 [:db_insert_placeholder_192] => 1266 [:db_insert_placeholder_193] => pl [:db_insert_placeholder_194] => 0 [:db_insert_placeholder_195] => domain_id [:db_insert_placeholder_196] => 2147483647 [:db_insert_placeholder_197] => 1 [:db_insert_placeholder_198] => 1 [:db_insert_placeholder_199] => 1 [:db_insert_placeholder_200] => 1266 [:db_insert_placeholder_201] => pl [:db_insert_placeholder_202] => 0 [:db_insert_placeholder_203] => domain_id [:db_insert_placeholder_204] => 1528372610 [:db_insert_placeholder_205] => 1 [:db_insert_placeholder_206] => 1 [:db_insert_placeholder_207] => 1 [:db_insert_placeholder_208] => 1266 [:db_insert_placeholder_209] => pl [:db_insert_placeholder_210] => 0 [:db_insert_placeholder_211] => domain_id [:db_insert_placeholder_212] => 2147483647 [:db_insert_placeholder_213] => 1 [:db_insert_placeholder_214] => 1 [:db_insert_placeholder_215] => 1 [:db_insert_placeholder_216] => 1266 [:db_insert_placeholder_217] => pl [:db_insert_placeholder_218] => 0 [:db_insert_placeholder_219] => domain_id [:db_insert_placeholder_220] => 2147483647 [:db_insert_placeholder_221] => 1 [:db_insert_placeholder_222] => 1 [:db_insert_placeholder_223] => 1 [:db_insert_placeholder_224] => 1266 [:db_insert_placeholder_225] => pl [:db_insert_placeholder_226] => 0 [:db_insert_placeholder_227] => domain_id [:db_insert_placeholder_228] => 2147483647 [:db_insert_placeholder_229] => 1 [:db_insert_placeholder_230] => 1 [:db_insert_placeholder_231] => 1 [:db_insert_placeholder_232] => 1266 [:db_insert_placeholder_233] => pl [:db_insert_placeholder_234] => 0 [:db_insert_placeholder_235] => domain_site [:db_insert_placeholder_236] => 0 [:db_insert_placeholder_237] => 1 [:db_insert_placeholder_238] => 0 [:db_insert_placeholder_239] => 0 ) in Drupal\Core\Entity\Sql\SqlContentEntityStorage->save() (line 805 of /Users/***/Desktop/****/**/***/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).`

If you can provide any advice much appreciated... P.S. my site has 5 domains and 6 languages....

**Comment by agentrickard** [comment]
@puogintas what versions of Drupal and Domain are you running?

**Comment by puogintas** [comment]
Hey,

I am using Drupal 8.40 and latest Domain version I believe Alpha 9...

From what more testing I done is that gid in node_access table is the same for 4 of my 5 domains.... 
What exactly gid stands for?

Thanks,
Pov

**Comment by agentrickard** [comment]
gid is the Grant ID, in this case the Domain ID number.

That suggests that your domains accidentally may have duplicate domain_id keys, which should not be possible, but might be affected by this bug: https://www.drupal.org/node/2908236

If you check the `domain.record.*` YML files for your site, look for the `domain_id` value. These should all be unique. Those files look like this:

```
uuid: 1d744d22-914f-4ffe-9b2f-3a1fbfbc1f07
langcode: en
status: true
dependencies: {  }
id: example_com
domain_id: 1702463808
hostname: example.com
name: 'Drupal 8'
scheme: http
weight: -1
is_default: false
```

If domain_ids aren't unique, we you likely have to edit them and reimport to reset the domain_id values. Then you'd have to run a node access rebuild.

I don't think this is fixable in any other way.

**Comment by puogintas** [comment]
Hey,

I did that via drush export / import configs and it was successful.

Cheers for all the help!!

Pov

**Comment by agentrickard** [comment]
@puogintas do you have any idea how you ended up with duplicate IDs in the first place?
