### ISSUE TITLE
Removing a domain does not remove its aliases

### ISSUE THREAD

**Issue by zerolab** [agentrickard/domain#378]
This makes for an interesting disconnect and validation error if you remove a domain, add it again with a different machine name, then try to create one the previous aliases.

I think this needs to implement `hook_ENTITY_TYPE_delete()` for domain and remove all attached aliases.

**Comment by agentrickard** [comment]
Agreed.

**Comment by agentrickard** [comment]
I wonder how we deal with this for Domain Config?

**Comment by agentrickard** [comment]
Thanks to jet lag, I was up early and fixed this, with a test. Could use a review.
