### ISSUE TITLE
Site frontpage

### ISSUE THREAD

**Issue by kim0051** [agentrickard/domain#392]
(Q1)
In D7 version, there is "Site frontpage".
In D8 version, I can't find "Site frontpage".

Where is it?
or How to specify "Site frontpage".

I read this in domain_config/README.md:
Currently, there is no user interface for changing settings, but you can load
in new files that contain configuration per domain.

I'll try.

(Q2)
And I clicked Ediors
( xxx.domain.com/admin/content/domain-editors/xxx_domain_com )
It appears as next.
The website encountered an unexpected error. Please try again later.
Anyway, thank you for your great works.

**Comment by zerolab** [comment]
#15 and the associated PR work towards your q1. 
Currently there is no UI for any of domain-specific configuration. But https://github.com/agentrickard/domain/tree/8.x-1.x/domain_config#usage explains what you need to do to make domain specific changes.

q2: there is not enough information. you do need to provide a stack trace from the server logs. Anything that would indicate what the error is. Doing the same on a couple of our sites, does not result in any error.

**Comment by kim0051** [comment]
q1 It works! Thanks!
q2 I'll check and I'll report.

**Comment by agentrickard** [comment]
I'm going to close this. Please re-open on drupal.org if the problem persists.
