### ISSUE TITLE
TypeError: Argument 2 passed to Drupal\domain\DomainListBuilder::__construct() php 7.1

### ISSUE THREAD

**Issue by elbertjose** [agentrickard/domain#399]
The website encountered an unexpected error. Please try again later.
TypeError: Argument 2 passed to Drupal\domain\DomainListBuilder::__construct() must implement interface Drupal\domain\DomainStorageInterface, instance of Drupal\webprofiler\Entity\Decorators\Config\ConfigEntityStorageDecorator given, called in /var/www/html/esdegue/modules/domain/domain/src/DomainListBuilder.php on line 94 in Drupal\domain\DomainListBuilder->__construct() (line 116 of modules/domain/domain/src/DomainListBuilder.php).

**Comment by andypost** [comment]
That's because webprofiler ptoxy services wrongly. Needs issue to be filed to devel module
