### ISSUE TITLE
Drupal can't boot because of domain config

### ISSUE THREAD

**Issue by franzwilding** [agentrickard/domain#40]
During initial request handling Drupal tries to access some configs: 

In \Drupal\Core\StackMiddleware\PageCache::handler()

    'system.performance'
    'cache.page.use_internal'

At this moment Drupal not all common functions are included. Domain config tries to get the current domain but depends on some functions, that are not included at this early stage like **entity_load_multiple_by_properties** or some other entity functions. 

I don't know, if Drupal shouldn't allow overrides on this early stage, or Domain config should check this and just return an empty array for overrides.

**Comment by agentrickard** [comment]
IMO: Drupal must allow overrides at this stage, and this is something that was working and I will raise it with AlexPott if it is no longer supported.
