### ISSUE TITLE
Test fails on Travis for PHP 7.2

### ISSUE THREAD

**Issue by agentrickard** [agentrickard/domain#402]
@zerolab I'm srring unexplained test fails -- i.e. with no useful debug information -- for 8.5.x and PHP 7.2.

Any ideas? https://travis-ci.org/agentrickard/domain/jobs/336294113

**Comment by zerolab** [comment]
Could it be related to https://www.drupal.org/project/drupal/issues/2927806 ?

**Comment by zerolab** [comment]
Will look tonight at amending the Travis config so PHP shows all errors/warnings

**Comment by agentrickard** [comment]
I suspect the 7.2 issue is a Travis issue:

```
7.2 is not pre-installed; installing
Downloading archive: https://s3.amazonaws.com/travis-php-archives/binaries/ubuntu/14.04/x86_64/php-7.2.tar.bz2
16.88s$ curl -s -o archive.tar.bz2 $archive_url && tar xjf archive.tar.bz2 --directory /
```

I'm going to remove it from the tests.
