### ISSUE TITLE
Drupal config infinity loop, when domain alias is installed

### ISSUE THREAD

**Issue by franzwilding** [agentrickard/domain#41]
I'm facing the problem, that domain_config runs into an infinity loop when domain_alias is installed. 

I think this is because domain_config tries to load the active domain by using domain aliases which will call domain_config to ask for any overrides. 

This may be linked to https://github.com/agentrickard/domain/issues/40

**Comment by agentrickard** [comment]
See also https://github.com/agentrickard/domain/issues/33

Domain Config was working fine until core rewrote the underlying system. It needs a major (and frustrating) rewrite.

Please do not file additional issues against it.

**Comment by agentrickard** [comment]
e.g. Don't expect it to work. Just don't enable Domain Config.
