### ISSUE TITLE
Travis tests failing re new $memory_cache on Entity storage classes

### ISSUE THREAD

**Issue by rivimey** [agentrickard/domain#423]
Travis tests are failing for D8.6 builds, but not 8.5. The relevant error message is:

      3x: The $memory_cache parameter was added in Drupal 8.6.x and will be
    required in 9.0.0. See https://www.drupal.org/node/2973262
        3x in DomainConditionTest::testConditions from
    Drupal\Tests\domain\Functional\Condition

The linked node is a change record resulting from the recent commit of: https://www.drupal.org/project/drupal/issues/1596472

Although the change record is somewhat opaque I think the problem is related to class DomainStorage and class DomainAliasStorage, which should both now have additional constructor parameters.

**Comment by rivimey** [comment]
See also https://www.drupal.org/project/domain/issues/2976895

**Comment by agentrickard** [comment]
Ah, I haven't committed the related PR yet. You can pull that from this commit.

https://github.com/agentrickard/domain/pull/418/commits/c7c4072afd196dd1fc538bee5375572d98894f45

**Comment by agentrickard** [comment]
I just cherry-picked that commit into the 8.x-1.x branch to unblock everything you're working on. So a rebase should fix things.
