### ISSUE TITLE
Get EntityTypeManager objects consistently

### ISSUE THREAD

**Issue by rivimey** [agentrickard/domain#424]
The module uses two ways to get an entityTypeManager object

a)  \Drupal::entityTypeManager()
b)  \Drupal::service('entity_type.manager')

These should be brought into sync by converting (b) into (a).

**Comment by rivimey** [comment]
Created PR #430 to address.

**Comment by zerolab** [comment]
This can now be closed.
👍 for taking the time to revisit and clean up. I so wish my project timelines would give me some more time to contribute to this module.

**Comment by rivimey** [comment]
Thanks :-)
