### ISSUE TITLE
DomainAccessManager parameter EntityInterface

### ISSUE THREAD

**Issue by rivimey** [agentrickard/domain#429]
Phpstorm is complaining to me that function getAccessValues() in DomainAccessManager cannot call hasField() on $entity because it is not in the interface, which is quite true.

At present, I believe Domain Access module requires FieldableEntityInterface entities because of the use of 'field_domain_access' and 'field_domain_all_affiliates', so it seems to me that we should not use EntityInterface:

- in DomainAccessManagerInterface::getAccessValues()
- in DomainAccessManagerInterface::getAllValue()
- in DomainAccessManagerInterface::checkEntityAccess()

and elsewhere in domain_access.module.

**Comment by agentrickard** [comment]
That seems correct.

**Comment by rivimey** [comment]
Created https://www.drupal.org/project/domain/issues/2979581 to track fix
