### ISSUE TITLE
Limited number of domains because of the UI

### ISSUE THREAD

**Issue by Kwadz** [agentrickard/domain#440]
As I quickly explained [here](https://www.drupal.org/project/drupal/issues/2996988), the current way to manage different domains does not allow to manage a lot of domains. I'd say 10 as a maximum because of the UI. 

Instead, a new form with filtering would allow to manage unlimited domains. That's why I suggest to  implement this feature. What do you think ?

**Comment by agentrickard** [comment]
If you can solve the UI problem -- which is both for administration and content creation -- then we should. That multisite issue isn't really relevant here.

**Comment by agentrickard** [comment]
Pro ablyr on Drupal.org. Just link the new issue here.

**Comment by Kwadz** [comment]
I opened a [new issue on drupal.org](https://www.drupal.org/project/domain/issues/3002849).
