### ISSUE TITLE
8.x-1.0-alpha14 - core functionality ok for use on a production environment?

### ISSUE THREAD

**Issue by ejanus** [agentrickard/domain#458]
I'm looking to use the domain module starting with 8.x-1.0-alpha14. 

I only need very minimal functionality. Namely, I need to detect the domain, and swap out a menu, or, add a default body class to write some custom CSS. 

Are there any indications that the current API will be changed significantly going forward?

Basically, for now, I'll be installing only the core domain module functionality and, no current plan to use any of the included sub-modules.

**Comment by agentrickard** [comment]
API is stable.
