### ISSUE TITLE
Own module config

### ISSUE THREAD

**Issue by Adamation** [agentrickard/domain#469]
I built a simple module that exposes a couple of fields as a config page and makes them available as a token.

In then used *hook_domain_config route_allowed_alter* to create domain versions of the config.

This was all working untill recently updating Drupal core.

Now things don't quite behave correctly. The config fields still set in the config table in the db for each domain. But in the Form controller the default value doesn't pull in the correct value. 

Could you shed some light on this issue, happy to go into further details.

**Comment by agentrickard** [comment]
I don't know what `hook_domain_config_route_allowed_alter()` is. That's not part of this module.

All of our UI work for Domain Config is here --  https://github.com/agentrickard/domain/pull/434
