### ISSUE TITLE
Can not find page

### ISSUE THREAD

**Issue by jrobertshawe** [agentrickard/domain#485]
I have installed all modules on 8.7.7 but for the life of me I can not get it working

I have added both domains in my local host file

I have added them is the domain records .  I can not access any basic page via the second domain URL also it fails the "Test server response" when saving.
If accessing the second URL without any page then it shows me the get started page (no front page configured )
Could any other modules be affecting the setup? (URL Alias)

**Comment by agentrickard** [comment]
I have been on vacation.

This behavior is generally a DNS problem. The "test server response" tries to load a known file location using your domain. If that fails to return a 200 response, then you have a DNS problem.

Make sure of the following:

* All of your DNS records / hostfiles point to the same Drupal installation and same settings.php file
* Do not try to set a base_url value in settings.php

You might also have to check your login cookies if anonymous users cannot normally access content. See the README for information.
