### ISSUE TITLE
Support for Webform module in Drupal 8

### ISSUE THREAD

**Issue by governmentSponsored** [agentrickard/domain#496]
First off, this is an excellent module and the **alpha16** release is working very well! Would love to use it in an upcoming project, which relies on the webform module.

Is supporting the webform module in the roadmap for the Drupal 8 domain module?  There was a [module created for D7](https://www.drupal.org/project/domain_webform) that appears to do what we're looking for, but work seems to have started/stopped on the [D8 version](https://www.drupal.org/project/domain_webform/issues/2961729) ([see relevant github repo](https://github.com/h3rj4n/domain_webform)).

Some webform support is handling with `domain_admin` module within this repo., but wasn't sure if this functionality would be expanded in the future. Didn't see it in the changelog (https://github.com/agentrickard/domain/blob/8.x-1.x/CHANGELOG.md).

**Comment by agentrickard** [comment]
No. Supporting one-off modules is out of scope.
