### ISSUE TITLE
Content not restricted for anonymous user

### ISSUE THREAD

**Issue by greenleafmedia** [agentrickard/domain#503]
We have the module installed, all options appear to be present in the admin, and multiple sites are rendering the correct theme based off of the domain.  However, it appears that anonymous users are able to access nodes across all domains (wrapped in different themes) no matter how we have the content assigned in the backend.

If I'm understanding the functionality correctly, it seems like domains which are not tagged for given content should throw 404 errors when accessed.  Am I doing something wrong on my end or am I misunderstanding the functionality of this model?  I appreciate any help you can give.

**Comment by agentrickard** [comment]
Support is handled on drupal.org.
