### ISSUE TITLE
Link to set a theme as default for a domain is missing domain_config_ui_domain querystring

### ISSUE THREAD

**Issue by BurningDog** [agentrickard/domain#520]
This is a bug report. I'm using the `domain` version 8.x-1.0-beta2 on `drupal` 9.1.4. I've enabled these modules: `domain`, `domain_access`, `domain_config`, `domain_config_ui`, `domain_content`.

### My goal

I'd like to set a theme as default for a domain (called `example`) at `/admin/appearance`.

### What I did

On that page I select the domain from the `Domain Configuration` and the url correctly changes to `/admin/appearance?domain_config_ui_domain=example&domain_config_ui_language`.

If I click the `Set as default` link the theme is incorrectly set as default for all domains instead of just for the `example` domain.

### The problem

The `Set as default` link for the desired theme for that domain is incorrect. It is
`/admin/appearance/default?theme=material_admin&token=[redacted]` but it should be
`/admin/appearance/default?domain_config_ui_domain=example&theme=material_admin&token=[redacted]`

 If I paste the 2nd link into the address bar, then the theme is correctly set as default for the desired domain (and that domain only).

### The solution

The `Set as default` link should include a `domain_config_ui_domain=[domain]` querystring.

**Comment by agentrickard** [comment]
Confirmed. 

The same is also true for `Install and set as default.`

**Comment by agentrickard** [comment]
It has been a long time since I looked at this code, which I believe worked fine in Drupal 8.x.

The issue seems to be that these are links, not form submits. The SESSION variable doesn't seem to be read, either, which means that we need a custom handler to rewrite the links on this page to include Domain and Language settings.

**Comment by agentrickard** [comment]
I would prefer to track this on drupal.org.
