### ISSUE TITLE
Mark old functions @deprecated

### ISSUE THREAD

**Issue by Crell** [agentrickard/domain#59]
There are many functions in domain.module still, which were in the D7 version, too.  Most are now just stubs for D8-style services.  Eg: 

All of those should be marked @deprecated, including when you expect to remove the function and what devs should do instead.  That helps ease the transition and points them in the right place to update their code.  Also, many IDEs will  note @deprecated and call that out when someone uses such a function, which helps even more.

**Comment by agentrickard** [comment]
Corrected in #71
