### ISSUE TITLE
Place block in CurrentDomainContext.php

### ISSUE THREAD

**Issue by siilak** [agentrickard/domain#74]
If I go admin/structure/block
and try to click "Place block", then I get error in my browser console
An AJAX HTTP error occurred.
HTTP Result Code: 200
Debugging information follows.
Path: /admin/structure/block/library/mythemename?region=topmenu
StatusText: OK
ResponseText: 
Fatal error:  Call to protected method Drupal\Core\Plugin\Context\Context::setContextValue() from context 'Drupal\domain\ContextProvider\CurrentDomainContext' in "mydomain.com"/modules/domain/domain/src/ContextProvider/CurrentDomainContext.php on line 42

If I comment out CurrentDomainContext.php
$context->setContextValue($current_domain);

Then "Place block" is working, but this is temporary, I think.

After uncomment these line, then I get
Fatal error: Call to protected method Drupal\Core\Plugin\Context\Context::setContextValue() from context 'Drupal\domain\ContextProvider\CurrentDomainContext' in /mydomain.com/modules/domain/domain/src/ContextProvider/CurrentDomainContext.php on line 42

**Comment by agentrickard** [comment]
I see. Core changed the method signature there.

This is addressed in #75 and ready for testing.
